package transfer_pvc

import (
	"crypto/aes"
	"crypto/cipher"
	"encoding/base64"
	"strings"
	"testing"

	"github.com/sirupsen/logrus"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
)

func TestRcloneObscure(t *testing.T) {
	original := "test-encryption-password-42"
	obscured, err := rcloneObscure(original, logrus.StandardLogger())
	if err != nil {
		t.Fatalf("rcloneObscure() error: %v", err)
	}
	if obscured == "" {
		t.Fatal("rcloneObscure() returned empty string")
	}
	if obscured == original {
		t.Error("obscured value should differ from original")
	}

	// Round-trip: reveal the obscured value using the same algorithm
	revealed, err := rcloneReveal(obscured)
	if err != nil {
		t.Fatalf("rcloneReveal() error: %v", err)
	}
	if revealed != original {
		t.Errorf("round-trip failed: got %q, want %q", revealed, original)
	}
}

func TestRcloneObscure_DifferentOutputEachCall(t *testing.T) {
	a, _ := rcloneObscure("same-input", logrus.StandardLogger())
	b, _ := rcloneObscure("same-input", logrus.StandardLogger())
	if a == b {
		t.Error("two calls with same input should produce different output (random IV)")
	}
}

func TestGenerateCryptSection(t *testing.T) {
	section, err := generateCryptSection("remote:my-bucket/ns/pvc", logrus.StandardLogger())
	if err != nil {
		t.Fatalf("generateCryptSection() error: %v", err)
	}

	for _, want := range []string{"[encrypted]", "type = crypt", "remote = remote:my-bucket/ns/pvc", "password = "} {
		if !strings.Contains(section, want) {
			t.Errorf("output missing %q, got:\n%s", want, section)
		}
	}

	// Verify the password field is non-empty
	for _, line := range strings.Split(section, "\n") {
		if strings.HasPrefix(line, "password = ") {
			pw := strings.TrimPrefix(line, "password = ")
			if pw == "" {
				t.Error("password should not be empty")
			}
		}
	}
}

func TestHasRcloneSection(t *testing.T) {
	tests := []struct {
		name   string
		config string
		want   bool
	}{
		{
			name: "actual section",
			config: `[remote]
type = s3
[encrypted]
type = crypt
`,
			want: true,
		},
		{
			name: "BOM-prefixed section",
			config: "\uFEFF[encrypted]\n" +
				"type = crypt\n",
			want: true,
		},
		{
			name: "section with trailing comment",
			config: `[encrypted] # generated by a prior run
type = crypt
`,
			want: true,
		},
		{
			name: "comment mentioning section",
			config: `[remote]
type = s3
# do not add an [encrypted] section here
`,
			want: false,
		},
		{
			name: "setting value mentioning section",
			config: `[remote]
note = [encrypted]
`,
			want: false,
		},
		{
			name: "similarly named section is not a collision",
			config: `[encrypted-backup]
type = crypt
`,
			want: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := hasRcloneSection([]byte(tt.config), "encrypted"); got != tt.want {
				t.Errorf("hasRcloneSection() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestCheckRclonePartialSuccess(t *testing.T) {
	tests := []struct {
		name    string
		output  string
		wantErr bool
	}{
		{
			name:    "no stats in output",
			output:  "some random log output\nERROR: something broke\n",
			wantErr: true,
		},
		{
			name:    "zero files transferred",
			output:  "ERROR : permission denied\nTransferred:            0 / 5, 0%\n",
			wantErr: true,
		},
		{
			name: "permission error only — partial success",
			output: "ERROR : .mongodb: failed to open directory \".mongodb\": open /data/.mongodb: permission denied\n" +
				"Transferred:           22 / 22, 100%\n",
			wantErr: false,
		},
		{
			name:    "all files transferred no errors — should not reach this func but handle gracefully",
			output:  "Transferred:           10 / 10, 100%\n",
			wantErr: true, // no ERROR but pod failed — genuine failure
		},
		{
			name: "non-permission error",
			output: "ERROR : network timeout\n" +
				"Transferred:            5 / 10, 50%\n",
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := checkRclonePartialSuccess(tt.output, "test-pod", "test-ns", logrus.StandardLogger())
			if (err != nil) != tt.wantErr {
				t.Errorf("checkRclonePartialSuccess() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func makeValidateCmd(srcNS, destNS string) *TransferPVCCommand {
	return &TransferPVCCommand{
		Flags: Flags{
			PVC: PvcFlags{
				Name:      mappedNameVar{source: "my-pvc", destination: "my-pvc"},
				Namespace: mappedNameVar{source: srcNS, destination: destNS},
			},
		},
	}
}

func rcloneSecret(name, namespace string, confData []byte) *corev1.Secret {
	return &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: namespace},
		Data:       map[string][]byte{"rclone.conf": confData},
	}
}

func TestValidateRcloneConfigSecret(t *testing.T) {
	scheme := newTestScheme()
	validConf := []byte("[my-remote]\ntype = s3\n")

	tests := []struct {
		name     string
		srcObjs  []runtime.Object
		destObjs []runtime.Object
		wantErr  bool
		wantMsg  string
	}{
		{
			name:     "both clusters have a valid secret",
			srcObjs:  []runtime.Object{rcloneSecret("my-secret", "src-ns", validConf)},
			destObjs: []runtime.Object{rcloneSecret("my-secret", "dest-ns", validConf)},
			wantErr:  false,
		},
		{
			name:     "secret missing on source cluster",
			srcObjs:  []runtime.Object{},
			destObjs: []runtime.Object{rcloneSecret("my-secret", "dest-ns", validConf)},
			wantErr:  true,
			wantMsg:  `"my-secret" (namespace "src-ns", source cluster)`,
		},
		{
			name:     "secret missing on destination cluster",
			srcObjs:  []runtime.Object{rcloneSecret("my-secret", "src-ns", validConf)},
			destObjs: []runtime.Object{},
			wantErr:  true,
			wantMsg:  `"my-secret" (namespace "dest-ns", destination cluster)`,
		},
		{
			name:     "source secret has empty rclone.conf value",
			srcObjs:  []runtime.Object{rcloneSecret("my-secret", "src-ns", []byte{})},
			destObjs: []runtime.Object{rcloneSecret("my-secret", "dest-ns", validConf)},
			wantErr:  true,
			wantMsg:  "missing",
		},
		{
			name:     "destination secret has empty rclone.conf value",
			srcObjs:  []runtime.Object{rcloneSecret("my-secret", "src-ns", validConf)},
			destObjs: []runtime.Object{rcloneSecret("my-secret", "dest-ns", []byte{})},
			wantErr:  true,
			wantMsg:  "missing",
		},
		{
			name:     "source secret has whitespace-only rclone.conf value",
			srcObjs:  []runtime.Object{rcloneSecret("my-secret", "src-ns", []byte("   \n\t  "))},
			destObjs: []runtime.Object{rcloneSecret("my-secret", "dest-ns", validConf)},
			wantErr:  true,
			wantMsg:  "missing",
		},
		{
			name:     "destination secret has whitespace-only rclone.conf value",
			srcObjs:  []runtime.Object{rcloneSecret("my-secret", "src-ns", validConf)},
			destObjs: []runtime.Object{rcloneSecret("my-secret", "dest-ns", []byte("   \n\t  "))},
			wantErr:  true,
			wantMsg:  "missing",
		},
		{
			name: "source secret has wrong key name instead of rclone.conf",
			srcObjs: []runtime.Object{&corev1.Secret{
				ObjectMeta: metav1.ObjectMeta{Name: "my-secret", Namespace: "src-ns"},
				Data:       map[string][]byte{"rclone-config": validConf},
			}},
			destObjs: []runtime.Object{rcloneSecret("my-secret", "dest-ns", validConf)},
			wantErr:  true,
			wantMsg:  "missing",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cmd := makeValidateCmd("src-ns", "dest-ns")
			srcClient := fake.NewClientBuilder().WithScheme(scheme).WithRuntimeObjects(tt.srcObjs...).Build()
			destClient := fake.NewClientBuilder().WithScheme(scheme).WithRuntimeObjects(tt.destObjs...).Build()

			err := cmd.validateRcloneConfigSecret("my-secret", srcClient, destClient)
			if (err != nil) != tt.wantErr {
				t.Errorf("validateRcloneConfigSecret() error = %v, wantErr %v", err, tt.wantErr)
			}
			if tt.wantErr && !strings.Contains(err.Error(), tt.wantMsg) {
				t.Errorf("validateRcloneConfigSecret() error = %q, want to contain %q", err.Error(), tt.wantMsg)
			}
		})
	}
}

// rcloneReveal decodes an rclone-obscured value for testing round-trips.
func rcloneReveal(obscured string) (string, error) {
	key := []byte{
		0x9c, 0x93, 0x5b, 0x48, 0x73, 0x0a, 0x55, 0x4d,
		0x6b, 0xfd, 0x7c, 0x63, 0xc8, 0x86, 0xa9, 0x2b,
		0xd3, 0x90, 0x19, 0x8e, 0xb8, 0x12, 0x8a, 0xfb,
		0xf4, 0xde, 0x16, 0x2b, 0x8b, 0x95, 0xf6, 0x38,
	}
	ciphertext, err := base64.RawURLEncoding.DecodeString(obscured)
	if err != nil {
		return "", err
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return "", err
	}
	buf := ciphertext[aes.BlockSize:]
	iv := ciphertext[:aes.BlockSize]
	stream := cipher.NewCTR(block, iv)
	stream.XORKeyStream(buf, buf)
	return string(buf), nil
}

// podWithContainerStatuses builds a Pod carrying the given container statuses.
func podWithContainerStatuses(name string, statuses ...corev1.ContainerStatus) *corev1.Pod {
	return &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: "test-ns"},
		Status:     corev1.PodStatus{ContainerStatuses: statuses},
	}
}

const startErrorMsg = `exec: "rclone": executable file not found in $PATH`

func TestCaptureTerminationReason(t *testing.T) {
	waiting := corev1.ContainerStatus{
		Name: "rclone",
		State: corev1.ContainerState{
			Waiting: &corev1.ContainerStateWaiting{Reason: "ImagePullBackOff", Message: "back-off pulling image"},
		},
	}
	startError := corev1.ContainerStatus{
		Name: "rclone",
		State: corev1.ContainerState{
			Terminated: &corev1.ContainerStateTerminated{ExitCode: 128, Reason: "StartError", Message: startErrorMsg},
		},
	}
	running := corev1.ContainerStatus{
		Name:  "rclone",
		State: corev1.ContainerState{Running: &corev1.ContainerStateRunning{}},
	}
	terminatedNoReason := corev1.ContainerStatus{
		Name:  "rclone",
		State: corev1.ContainerState{Terminated: &corev1.ContainerStateTerminated{ExitCode: 1}},
	}

	tests := []struct {
		name          string
		pod           *corev1.Pod
		containerName string
		want          string
	}{
		{
			name:          "nil pod",
			pod:           nil,
			containerName: "rclone",
			want:          "",
		},
		{
			name:          "no container statuses",
			pod:           &corev1.Pod{},
			containerName: "rclone",
			want:          "",
		},
		{
			name:          "container name not found",
			pod:           podWithContainerStatuses("p", startError),
			containerName: "not-rclone",
			want:          "",
		},
		{
			name:          "terminated with StartError reason",
			pod:           podWithContainerStatuses("p", startError),
			containerName: "rclone",
			want:          "container terminated: StartError: " + startErrorMsg,
		},
		{
			name:          "waiting with reason",
			pod:           podWithContainerStatuses("p", waiting),
			containerName: "rclone",
			want:          "container waiting: ImagePullBackOff: back-off pulling image",
		},
		{
			name:          "running has no termination reason",
			pod:           podWithContainerStatuses("p", running),
			containerName: "rclone",
			want:          "",
		},
		{
			name:          "terminated without a reason is ignored",
			pod:           podWithContainerStatuses("p", terminatedNoReason),
			containerName: "rclone",
			want:          "",
		},
		{
			name:          "matches the named container among several",
			pod:           podWithContainerStatuses("p", running, startError),
			containerName: "rclone",
			// both statuses are named "rclone"; the first match (running) wins
			want: "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := captureTerminationReason(tt.pod, tt.containerName); got != tt.want {
				t.Errorf("captureTerminationReason() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestPodTerminationReason(t *testing.T) {
	scheme := newTestScheme()
	startErrPod := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{Name: "rclone-upload", Namespace: "test-ns"},
		Status: corev1.PodStatus{
			Phase: corev1.PodFailed,
			ContainerStatuses: []corev1.ContainerStatus{{
				Name: "rclone",
				State: corev1.ContainerState{
					Terminated: &corev1.ContainerStateTerminated{ExitCode: 128, Reason: "StartError", Message: startErrorMsg},
				},
			}},
		},
	}

	tests := []struct {
		name          string
		objs          []runtime.Object
		podName       string
		containerName string
		want          string
	}{
		{
			name:          "pod found with StartError container",
			objs:          []runtime.Object{startErrPod},
			podName:       "rclone-upload",
			containerName: "rclone",
			want:          "container terminated: StartError: " + startErrorMsg,
		},
		{
			name:          "pod not found returns empty",
			objs:          nil,
			podName:       "does-not-exist",
			containerName: "rclone",
			want:          "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			c := fake.NewClientBuilder().WithScheme(scheme).WithRuntimeObjects(tt.objs...).Build()
			got := podTerminationReason(c, tt.podName, "test-ns", tt.containerName, logrus.StandardLogger())
			if got != tt.want {
				t.Errorf("podTerminationReason() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestCheckRclonePartialSuccessTerminationDetail(t *testing.T) {
	reason := "container terminated: StartError: " + startErrorMsg

	t.Run("no rclone output appends termination detail", func(t *testing.T) {
		err := checkRclonePartialSuccess("", "rclone-upload", "test-ns", logrus.StandardLogger(), reason)
		if err == nil {
			t.Fatal("expected error when no file count is found")
		}
		if !strings.Contains(err.Error(), reason) {
			t.Errorf("error %q should contain termination detail %q", err.Error(), reason)
		}
	})

	t.Run("partial success wins even with a termination reason", func(t *testing.T) {
		output := "ERROR : .mongodb: permission denied\nTransferred:           22 / 22, 100%\n"
		if err := checkRclonePartialSuccess(output, "rclone-upload", "test-ns", logrus.StandardLogger(), reason); err != nil {
			t.Errorf("expected nil (partial success) even with termination reason, got %v", err)
		}
	})

	t.Run("empty termination reason adds no parens", func(t *testing.T) {
		err := checkRclonePartialSuccess("", "rclone-upload", "test-ns", logrus.StandardLogger(), "")
		if err == nil {
			t.Fatal("expected error")
		}
		if strings.Contains(err.Error(), "()") {
			t.Errorf("error %q should not contain empty detail parentheses", err.Error())
		}
	})

	t.Run("no variadic arg behaves like before", func(t *testing.T) {
		err := checkRclonePartialSuccess("", "rclone-upload", "test-ns", logrus.StandardLogger())
		if err == nil {
			t.Fatal("expected error")
		}
		if strings.Contains(err.Error(), "(") {
			t.Errorf("error %q should not contain a detail suffix", err.Error())
		}
	})
}
