apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDMjCCAhqgAwIBAgIIOSqkxL8shAowDQYJKoZIhvcNAQELBQAwNzESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSEwHwYDVQQDExhrdWJlLWFwaXNlcnZlci1sYi1zaWduZXIw
    HhcNMjYwNjI1MDQxMDAyWhcNMzYwNjIyMDQxMDAyWjA3MRIwEAYDVQQLEwlvcGVu
    c2hpZnQxITAfBgNVBAMTGGt1YmUtYXBpc2VydmVyLWxiLXNpZ25lcjCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBAMzoABnLCrZ249dkjN5X3+Cw+sR5sdVt
    /wJVLe9HpA0IJro5pjRrcZ7n38RU+iyEHXFzNgqU0sTEwl6IaMCy6QyXUXOujCSN
    0AXhExNwNmbQNkJxBhLLUQRhAW+z8c4H02lp6+hnk8EyXyI+xNnCyF8pgOrCPeCz
    Es5kZRiYNxORW9JTbdcJgwpIjq+ghf8cr+jAs4UZxI3ERV3+yrmjw9fCLXrISFOZ
    v4+UdB46jZ0fKmsZzJCGWEGS3yLlrxP51mGnN09Ia7hjV4K3OZUZNZAOgOj15nOd
    R41DQ4MGJSIZbFMtBPItssdB+XtNHubZ83It+4iix/kQar4sSOiJ8SUCAwEAAaNC
    MEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFK0/
    TZQFi1cQt0qeembf44NG1Bb0MA0GCSqGSIb3DQEBCwUAA4IBAQBDuXGNIIjwZGm3
    IpWyWawV90cuPgWhFDDV2ZS78VCCgbAf90KTknNM48TCAooPvhJ/xVQMj7fOdqbC
    SUCvnJxx0gepqeOeFsr0Nb+3NlZD6hX+0jWt8ZYPmgKm2qVIk3ZWEWeSC9QZqTa+
    Je5AHWtrrLy+Dwrm5eeff0L8pImxp0GPsiEIrURsrDFaZ9sUWX8NyvWkEE/WeqWv
    7zpqvBemPKHohA6K5Hhs++9V2Y11vNPedup4fjFXeilaz0+iRfqyeTjtgwRLJonl
    OYOmiTsQu3axfXZmSgqgo+SMb6IJl4dKkyVd1TS20hLiJJDcdfQEjIRyN2NH8a/4
    fP2PRp1a
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDQDCCAiigAwIBAgIIVjMwtpF7dcAwDQYJKoZIhvcNAQELBQAwPjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSgwJgYDVQQDEx9rdWJlLWFwaXNlcnZlci1sb2NhbGhvc3Qt
    c2lnbmVyMB4XDTI2MDYyNTA0MTAwMVoXDTM2MDYyMjA0MTAwMVowPjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSgwJgYDVQQDEx9rdWJlLWFwaXNlcnZlci1sb2NhbGhvc3Qt
    c2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxcD5Fz2nKo0S
    lVxkpcssT6MbFPW+s+P0Xe4EjR2rJ0bxteZSS8Muz89M3yGqtXEfyQFQ3o3Bd0HD
    AMxF0D4KKtvXHBC1eOzVdsznA3aA+SAg9YLIFkxYMo91r+tlWR6r2T98Qkz+mtRG
    jSwQpXqUpJxrE6R2Ti5tbgInJdH5s/3DaPLQqLepRyJga8S5+c3gWi9A/9NsUL4E
    6ehML4xxZRhz0EGaPM8qq7RQzYRI4pmeAVskYBVMabZVfPU3j9FtTMwJUi2hiBdP
    zzAqAFgkLIInFuv2xLS58V4SxJSx//0ewu4fIkzfmamWb1Rs5u1N2uJ5UBX32xxf
    xv2FdOot4QIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB
    /zAdBgNVHQ4EFgQUqgm5/3GAo5XfG0YtowTmjKFmzswwDQYJKoZIhvcNAQELBQAD
    ggEBABjW/SghZAky3/PPUmNVudwN++D2lQ3RqeWbFaQ40LJnUzHuws9WfV4FJ8IM
    K8+YaaEzSIu8m1MUnfLjpc6iGom+Mdx1v5eNTaDf+7obMLIKiTBsbcqR/SxoVrEa
    F5I1/ovY+lf02qbwRs0Oz7mXsEfuNv6bN8MuBEkynutTJ3xbsXOxOnM6vEq/eBiD
    i4o/iDGgGUyO2Cy1VParGswLhbPFNmRrToV8XtfhGsunv8rPmSgCuf6/N/GrbVVR
    2j39hmbhfwV7kJimIMZe66HyjuYAOrKnrO871cOK37uzRtv2x1OJ5OHPaRiNwPZf
    UeYz2l2TZUHvdZXoTR2b6Fi2GOA=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIIZnzkco2FTwMwDQYJKoZIhvcNAQELBQAwRDESMBAGA1UE
    CxMJb3BlbnNoaWZ0MS4wLAYDVQQDEyVrdWJlLWFwaXNlcnZlci1zZXJ2aWNlLW5l
    dHdvcmstc2lnbmVyMB4XDTI2MDYyNTA0MTAwMVoXDTM2MDYyMjA0MTAwMVowRDES
    MBAGA1UECxMJb3BlbnNoaWZ0MS4wLAYDVQQDEyVrdWJlLWFwaXNlcnZlci1zZXJ2
    aWNlLW5ldHdvcmstc2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
    AQEA5zXbUquPxSUQof8rYhWi8EsCpnu9cJKarRy0EkV810Xli+KXhA0JrgPi7fGM
    8iwYr+Z6d4j1IO+8xLsMRryNcu+HaQmZ6q0uCXHOuWv7EfmNhC5Nt47RbHB6UERm
    R1A0Yd8AjAvvLgWqFY/Xdr3/uONXHqwOyrYebrr4o1nWfl3ZthErWfu4FjBNuRfk
    JIlV+Xsnf7esz8UGfJiGActU4Qi3I0w4h1WmXr+tw4tLirTatdqEBnf6JOC9J+7k
    ePnvc82mnvVEzsYMXA+jmIQ36Tej8WKqO2e+CcWh2zpQ/BcbS/mn8Ar8Y7c5GH6i
    GVcnZd33GYDoHrX/6M8NYrve2QIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYD
    VR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUNXhjune8uGxqR9od2G/5uHdW14gwDQYJ
    KoZIhvcNAQELBQADggEBAAhv85qIPwpT6Kq4oYMRQPEXUkx7BlS3Ey97ft6e6qCt
    V7XsAGm+D4YrxrSxXi9+IY9yHpqgrKOAir6zXOEzlyHiUd0BY+xdz0xcCej9g9z0
    sGlAPva2Srp5k5kWSPu4UMDxzB8xmCxeut2AYA46Ppp7ztl7PMUTIVOrbqzIZ5Ei
    JFyI+cYNF6vTiBd5Q83I7kt94VQOvjzDG53EaT0Oy0m0YsZ7Xp0vEmdXzZxg1hcr
    HT0spCuuEsqdj51mf4agUebMcSL0YgNM0U58fwwGiFWA83K/ZaO3d2xm08x5CkiR
    acIuZj6yL7G50oeHBFhzAfID8kIUzGATzZDXJkqcdHE=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDlzCCAn+gAwIBAgIIXXtGUuYzsUMwDQYJKoZIhvcNAQELBQAwWTFXMFUGA1UE
    AwxOb3BlbnNoaWZ0LWt1YmUtYXBpc2VydmVyLW9wZXJhdG9yX2xvY2FsaG9zdC1y
    ZWNvdmVyeS1zZXJ2aW5nLXNpZ25lckAxNzgyMzYxNTgwMB4XDTI2MDYyNTA0MjYy
    MFoXDTM2MDYyMjA0MjYyMVowWTFXMFUGA1UEAwxOb3BlbnNoaWZ0LWt1YmUtYXBp
    c2VydmVyLW9wZXJhdG9yX2xvY2FsaG9zdC1yZWNvdmVyeS1zZXJ2aW5nLXNpZ25l
    ckAxNzgyMzYxNTgwMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4xPD
    E3+ODpJ9yt/+wlV6PW5FlPE9O/MnXs/vW8nWGiPxeH8m4S9OoEPvKCfWW52zckrU
    rc5Ju1h9hueSAui5y3NuR+TTt4BQLPPEWAeL1sMojoCmO7sDUqu4qCdOSGBJVt4l
    ENJtqLcX2IeNCOBkoF8E+j4r+h2jkK3+XMKND4GNHWLepdaXNYb6MQFsjbvwpQT7
    Fd7DVW/Uc4lBNnxWYCrNPpHjog+8n0CEJNDItOEjK36tFlLgM+2KI5+JuKqigG83
    L747azkpYepnpT9y+dodXEWmjT+MJGUFsKdiXD1W/RyXkv76U70FvGeKyDckISRD
    AyDMdjWtsvehPHcIdwIDAQABo2MwYTAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/
    BAUwAwEB/zAdBgNVHQ4EFgQUDk1B17IqC2yGxCLpELPuSeG7kdUwHwYDVR0jBBgw
    FoAUDk1B17IqC2yGxCLpELPuSeG7kdUwDQYJKoZIhvcNAQELBQADggEBABKBK4gD
    K2ZPduwhPU1XMvHuZN5XSQvltbCy4XbTdNWXiZWrUjx8VnWLMAZNSSPGDe7aOIAT
    L31wJq/Z5P7we9RPxn/eUEZjwnqJ7KPftX0K1gguUNLwMZeiE3PxWqpmLUz56DGj
    xOkJ6bMQggGObzFtkFY9bZZZscA4MwI0TBnumFhxr++bFlxqiuzbAxzg0Xb4kNYf
    YVygQR2FD41GxOdZEigXuXfpimDQkrF5PW5Siy6TOUh2A/jFCphDRy7H6Q/MCivi
    VhXT0HO5Cr5X/33HDvibqf3siTq4Fw4MAMEcNSL/yZ1C+Bg7uN/SfwQ5ctoakTP+
    bvgD2uIOh0IGZAw=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDkzCCAnugAwIBAgIIR1IE76LkN9cwDQYJKoZIhvcNAQELBQAwJjEkMCIGA1UE
    AwwbaW5ncmVzcy1vcGVyYXRvckAxNzgyMzYxNjU2MB4XDTI2MDYyNTA0Mjc0M1oX
    DTI4MDYyNDA0Mjc0NFowOTE3MDUGA1UEAwwuKi5hcHBzLm1pZ3FlLTUzMTMxLnFl
    LmRldmNsdXN0ZXIub3BlbnNoaWZ0LmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEP
    ADCCAQoCggEBAMjPeOUnIVDFTRhP8Z2xI/qNTW6ASP9cmr7qbFd6PpzvONQB/Ier
    G6TG4OyzMbcgA6rUNXTlCuctsO5fbdmlssQ01cHZi+gGcdPlmmg+vt9NXvym2Pc6
    UCOOtB7l+OCUIHlThqyHAp52E700VZ9G0GEbzIRmILYjcHnTIKh66Zt3mB/6Im8I
    wCL3gpDEppFUWfi913zEc08uS2Vsvrk2O91y8dxQqPXeOJIk7lorLWS//aDHqq2f
    dKqeN4En3bs7wxLfm0rXnUsfp+9nwNOqq/IIN6AmcFdGmvHp2ZtPBSedFJicPxMf
    NMdMu1zKiLX+CC6Vsk9bLrNvlZWW6xA+bOkCAwEAAaOBsTCBrjAOBgNVHQ8BAf8E
    BAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAdBgNVHQ4E
    FgQU+Y1rmBau65mHoD/sDu3DYW5Pa8EwHwYDVR0jBBgwFoAUJ08b+n2oHrQg7Y+A
    mxcUtQJVtmcwOQYDVR0RBDIwMIIuKi5hcHBzLm1pZ3FlLTUzMTMxLnFlLmRldmNs
    dXN0ZXIub3BlbnNoaWZ0LmNvbTANBgkqhkiG9w0BAQsFAAOCAQEAaM3/z7g3TBhv
    Xllo1dG20j+rpPwPb7LRCIOoLZoNNu6/7dFTQHI3QilD5u56iOpfRkQuoqueaqKf
    5BXLuEz51XcbH9SkNZXYksC0coH//EzNJNAYbM0JypxYYroj4QP6p6ZmEjZKhmyN
    bUpqUxlTtZCUPv2zwjwdsoOSujeMvQy3nhHWbm8zjDXJ6Vtcx/EKFra9w9IlF/6Q
    Ee2Cwi+fumKHEOmBUQ1K276X5ngbpwFGjGcDG+wT2WyWTHAd0jMhjEYd1UbLedEa
    4UNUxc/85zOx3H9nnlT6Aexu2ngvohy39hmmgrBI8sGQohsmSKlYFpgpVsGGiZTp
    H7avmye6KQ==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDDDCCAfSgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtpbmdy
    ZXNzLW9wZXJhdG9yQDE3ODIzNjE2NTYwHhcNMjYwNjI1MDQyNzQwWhcNMjgwNjI0
    MDQyNzQxWjAmMSQwIgYDVQQDDBtpbmdyZXNzLW9wZXJhdG9yQDE3ODIzNjE2NTYw
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCb+XDiw5tDEurr0I5W/1S6
    Zn68lUOjqTeWYcIESyE3FkVdd+pdANAt39eogsUV6TvLHlvFbIpocHrdDoyLE8Ep
    gSnotCjpAl4O5YPYiDJqo9pAI/ZDiYQHMwotg/UzH2WMwyWkk7UeVu3J7CTnhjRt
    RBEcmXVOSBfyUsefnRpMpUJ+dPpFnt0oQPxjg+it031yYfz8rk93FdSfTggxsWYf
    wp4nQemykUDOliNr0i5JJk7/cH5+vKJxBEfQ8QM2iu+jg5kIWkYVGBs/N5scJFIu
    qRCrNl3lFYQg8VmmGGqz2b28z22mC8TC5PirCQQrIjb330+9IE3pZlx/+3UsPtAF
    AgMBAAGjRTBDMA4GA1UdDwEB/wQEAwICpDASBgNVHRMBAf8ECDAGAQH/AgEAMB0G
    A1UdDgQWBBQnTxv6fagetCDtj4CbFxS1AlW2ZzANBgkqhkiG9w0BAQsFAAOCAQEA
    UpevT03TjZMhTrdAYOQhRXzJ1c3tQoM+CR0O+/ukoiuI+N8FvoeviCqO7CT9mloi
    UWiUvMhB9jgy8o8s84XLC62ej54scieqb//Dn5Sld5S+NeMzNxuhLkV6n9bBjafx
    KY3dpZOUELKuP5LeJIZXxL/bvtAcqk2mdA++PzDbgbSrXbKKR8Nq+VYvM7OFmsbF
    qOh4NOI6o26a4r1u2JMbol66i3IqUwk8NoUdBelFE4YIPlUL+mQBM0xN5h0AqJpr
    52mLW/FF0N9Vu/ftEDqKUbFEt//2GcNMiL2c139NqfLMsxKNtofOqDccNMLshuHl
    HCOxU3aOpQfK+TgkzJeWHg==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  creationTimestamp: "2026-06-25T05:47:03Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/description: {}
    manager: kube-controller-manager
    operation: Update
    time: "2026-06-25T05:47:03Z"
  name: kube-root-ca.crt
  namespace: simple-nginx-nopv
  resourceVersion: "44828"
  uid: 3f8f6ad7-5d44-475f-90fa-39170d20ac0c
