apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2026-06-25T05:47:06Z"
  labels:
    app: simple-nginx-nopv
    endpoints.kubernetes.io/managed-by: endpoint-controller
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:endpoints.kubernetes.io/last-change-trigger-time: {}
        f:labels:
          .: {}
          f:app: {}
          f:endpoints.kubernetes.io/managed-by: {}
      f:subsets: {}
    manager: kube-controller-manager
    operation: Update
    time: "2026-06-25T05:47:07Z"
  name: my-simple-nginx-nopv
  namespace: simple-nginx-nopv
  resourceVersion: "44883"
  uid: 432f5f66-8705-4401-a8f3-c0139bac42db
