apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    openshift.io/description: Allows deploymentconfigs in this namespace to rollout
      pods in this namespace.  It is auto-managed by a controller; remove subjects
      to disable.
  creationTimestamp: "2026-06-25T05:47:04Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:openshift.io/description: {}
      f:roleRef: {}
      f:subjects: {}
    manager: openshift-controller-manager
    operation: Update
    time: "2026-06-25T05:47:03Z"
  name: system:deployers
  namespace: simple-nginx-nopv
  resourceVersion: "44845"
  uid: abf08f85-093a-4ea8-af78-d258cf4ff1df
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:deployer
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: simple-nginx-nopv
