apiVersion: v1
data:
  .dockercfg: REDACTED
kind: Secret
metadata:
  annotations:
    openshift.io/internal-registry-auth-token.binding: bound
    openshift.io/internal-registry-auth-token.service-account: deployer
  name: deployer-dockercfg-rgp2c
  namespace: simple-nginx-nopv
  ownerReferences:
  - apiVersion: v1
    kind: ServiceAccount
    name: deployer
type: kubernetes.io/dockercfg
