apiVersion: v1
data:
  .dockercfg: REDACTED
kind: Secret
metadata:
  annotations:
    openshift.io/internal-registry-auth-token.binding: bound
    openshift.io/internal-registry-auth-token.service-account: default
  name: default-dockercfg-w99v8
  namespace: simple-nginx-nopv
  ownerReferences:
  - apiVersion: v1
    kind: ServiceAccount
    name: default
type: kubernetes.io/dockercfg
