apiVersion: v1
imagePullSecrets:
- name: deployer-dockercfg-rgp2c
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: deployer-dockercfg-rgp2c
  creationTimestamp: "2026-06-25T05:47:03Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:imagePullSecrets: {}
      f:metadata:
        f:annotations:
          f:openshift.io/internal-registry-pull-secret-ref: {}
      f:secrets:
        k:{"name":"deployer-dockercfg-rgp2c"}: {}
    manager: openshift.io/image-registry-pull-secrets_service-account-controller
    operation: Apply
    time: "2026-06-25T05:47:03Z"
  name: deployer
  namespace: simple-nginx-nopv
  resourceVersion: "44833"
  uid: 9095d1dc-0101-47b7-97d2-19aedbccc8e9
secrets:
- name: deployer-dockercfg-rgp2c
