apiVersion: v1
imagePullSecrets:
- name: default-dockercfg-w99v8
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: default-dockercfg-w99v8
  creationTimestamp: "2026-06-25T05:47:03Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:imagePullSecrets: {}
      f:metadata:
        f:annotations:
          f:openshift.io/internal-registry-pull-secret-ref: {}
      f:secrets:
        k:{"name":"default-dockercfg-w99v8"}: {}
    manager: openshift.io/image-registry-pull-secrets_service-account-controller
    operation: Apply
    time: "2026-06-25T05:47:03Z"
  name: default
  namespace: simple-nginx-nopv
  resourceVersion: "44832"
  uid: c80cdcd0-cc29-4797-a706-7e18ade5a7c1
secrets:
- name: default-dockercfg-w99v8
