apiVersion: v1
data:
  service-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDUTCCAjmgAwIBAgIIfL+yjA7wCEkwDQYJKoZIhvcNAQELBQAwNjE0MDIGA1UE
    Awwrb3BlbnNoaWZ0LXNlcnZpY2Utc2VydmluZy1zaWduZXJAMTc3NDg1OTMxOTAe
    Fw0yNjAzMzAwODI4MzlaFw0yODA1MjgwODI4NDBaMDYxNDAyBgNVBAMMK29wZW5z
    aGlmdC1zZXJ2aWNlLXNlcnZpbmctc2lnbmVyQDE3NzQ4NTkzMTkwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQC4CtLQ5KNhjAcYDV9UqnaGGJCeBi/Hj22g
    gEBg+Lk6hkcqTrDYDPO/tmqqg8CcWbUQyISWxPtut7Cj3TZv7GLY4je8BuLy0cNM
    6EMkOh+NIJI6ziydYXAgVyCLtK+W9EKqgZULcLwSvHkpGPrjAGBkJ+xqOqoMUv68
    s7W20Mmn1yukDaHVzeEJ4Ybco8KloHTCff+uW7OTcVWJnaDAyNbXHJbJrOK8KfHH
    tUd4hCwh88qfhgmCLGJfYn/bLEnesS516VZY7o3jbiJE1RueWo4Ds4BhaVbVj+8J
    z2euh4YvQ+O0rwDC5i+hPqXgZ+GURgOgPNPomd+TLbUvWs3D9VGtAgMBAAGjYzBh
    MA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBT3uMFs
    BwE7Iowz+w0nyPQ1I+APvDAfBgNVHSMEGDAWgBT3uMFsBwE7Iowz+w0nyPQ1I+AP
    vDANBgkqhkiG9w0BAQsFAAOCAQEAEKPVkX4Y5xaS5mGoDE7LCjj1MRNPegSUpDR6
    LDId2pOJgE69q6FqaCg6EUUMWeiLoBwrIRZqesw7dsGABwI6SNaRdeW7FOLf9RDF
    8u7zR6/7TE8J2YOp3M3IYUa9c+x+AZs+RW6TJper2nXvyi81HdTA25AbPdlcX065
    d/wzVwqCNxCU8/JbdEwHx021BNoUBWtqUZloFjnq9ycn28NfKmnQ+eDhnocP0h+n
    jgQxe21LIxoxkyFJZts0AEDdNz4QdezJ6yo3+nLHH6AqWY7FdsvytvOKkWq4uNP9
    mOyI5nEEGfGWldUCJ+IIuMQzCUf7iyuwjfyboF4A7zC0gIkjPA==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  creationTimestamp: "2026-03-30T15:21:32Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data: {}
      f:metadata:
        f:annotations:
          .: {}
          f:service.beta.openshift.io/inject-cabundle: {}
    manager: kube-controller-manager
    operation: Update
    time: "2026-03-30T15:21:32Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:service-ca.crt: {}
    manager: service-ca-operator
    operation: Update
    time: "2026-03-30T15:21:32Z"
  name: openshift-service-ca.crt
  namespace: crane-complex-demo
  resourceVersion: "157115"
  uid: f9fe21c7-2f5c-4c5e-a7b9-41dd85875712
