apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDMjCCAhqgAwIBAgIIP2GH2dWy218wDQYJKoZIhvcNAQELBQAwNzESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSEwHwYDVQQDExhrdWJlLWFwaXNlcnZlci1sYi1zaWduZXIw
    HhcNMjYwMzMwMDgxMzQ0WhcNMzYwMzI3MDgxMzQ0WjA3MRIwEAYDVQQLEwlvcGVu
    c2hpZnQxITAfBgNVBAMTGGt1YmUtYXBpc2VydmVyLWxiLXNpZ25lcjCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBALHTW0bKEti7DaJ/9cv8bQWLopkqn8V4
    WFbXSJJA1GErQUkwrfhjd7zXdQZYjNA0OuyrOLMU4dGUpM886qarmyT3hMFYkuBF
    WBBSfo7GPPEAtMmaeN7XBGnIoixw9598i/IhoDt1zDQRb+QSxya/ElgfDX84uc8k
    MIUmGIBBT3oa1WOW+2W+sQy5Rc+BBSBHhNFVUZ8CYxIuOYMn18kaUPV4cE003ZEw
    CzoZxZhdst/xdGazJ9C/6SY6tqIneN9+2INc7I9fh4WtvUtT114E+shDqySiShw9
    vz3DohAfgnrGsQuohPL2S7BadquGu3HWWdiVYCz4GgOrWqUfhlEn2oUCAwEAAaNC
    MEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFMft
    29zBKW6W/aLiNWkHkXFaXTT1MA0GCSqGSIb3DQEBCwUAA4IBAQCxREv1RtCBzj1C
    hiuGqTY4hZql+C8bLIM/QXJPNHowrH8rRTpE4zK2K8Raaa5u1kcLF+pfzl+CRFSJ
    4lu4wJ89V8nBe377cZ+LfAPwVpAjZe3hUgjVjjdVzGC+LY+gNtJDZUk85Jet8p7Y
    IT+diffGTXY8BVhVLEiAQLoiaXECTaJNKJO6jP6n672BOMXtY5Y/OSTmCdM+fSWi
    aLxXZ23vLzxrtyK3ZemyxbgaoZkSykkepFJHzP+ZijWEFGf5goPS0K66a4cvkjxR
    Se+GEKjdhNSbMCS8oylp0u2KICSZLB9LZtn6mnnCCB9JO+spmo8/hObpMHH2Ewv1
    WMhmTFVp
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDQDCCAiigAwIBAgIIUcpKDlULWvQwDQYJKoZIhvcNAQELBQAwPjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSgwJgYDVQQDEx9rdWJlLWFwaXNlcnZlci1sb2NhbGhvc3Qt
    c2lnbmVyMB4XDTI2MDMzMDA4MTM0M1oXDTM2MDMyNzA4MTM0M1owPjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSgwJgYDVQQDEx9rdWJlLWFwaXNlcnZlci1sb2NhbGhvc3Qt
    c2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm8UbQQ5MGeYu
    59120yXP6u1ESk0lFHr/N1UDl1ViEUNUByrG15+4P9Tr668qqy2w4J3kvOD7OMYP
    rVTs8tOFRTnxC7YobGxLG8AqSRidaJqI7eJ1scC3+gqpvNZCQB9ZllDwQioxLWpR
    cXXkOdaiRHO0wTz0XkrQuQCZqMpKhhaRf7xGtlJJuiY6uO0XdRew0HFHc1XQ+o2M
    Vhq9Ee6ecw24ym89wxempXim/Tbl/5ev7cvMFC90Wg4sTamxAuxQQlCWhgbAtj8p
    1FA9HiIEVccq8EkQpunjeWLX141Kcd0tvg6Xco3hIpo1Hka/RxFWGizEGSKWtdV7
    erOdzYEOiQIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB
    /zAdBgNVHQ4EFgQU8kshTuUlPdPFWpuW9I5xnO7f/ZQwDQYJKoZIhvcNAQELBQAD
    ggEBABB/W57lG9tNjWzm6vXGcgvkxRtIQAeWbQQwm2cy5bNbcD+RYZd45D43djyM
    fEM+x6YYWHWrevqrngU4rTgjtrD46SoAtwD+aarD9VvVUjhz6GJx8MQJAd0yCZ5w
    Q9LQYXnNWbgNVDZVpo3MUCPjEoyLJT9nuv+vpDJfzwTM8P+L+v+GRjfEogRDJSZL
    ZGCSeA2kIj//k1CQjYU8DG52Ef7CHpje1qoeZcJ+zhLgF1og94Ff6TcNMAjKvaND
    SBWz5iuukvGL0/sewh/NB16IXsDHWVJV39uvOOdUTUG2h5ecKu0kq1H+YsSKieUt
    tpWryNZTj6zD1T5fo3KxqzATG+U=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIIf7rnfeaYxZcwDQYJKoZIhvcNAQELBQAwRDESMBAGA1UE
    CxMJb3BlbnNoaWZ0MS4wLAYDVQQDEyVrdWJlLWFwaXNlcnZlci1zZXJ2aWNlLW5l
    dHdvcmstc2lnbmVyMB4XDTI2MDMzMDA4MTM0NFoXDTM2MDMyNzA4MTM0NFowRDES
    MBAGA1UECxMJb3BlbnNoaWZ0MS4wLAYDVQQDEyVrdWJlLWFwaXNlcnZlci1zZXJ2
    aWNlLW5ldHdvcmstc2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
    AQEAt23yjhr0g77o6SUdT/l4Qhb6H9XWMdnlIQtB2k2aOUt5QHZaYnhtJhWTflbm
    A5OPUF88WLYvj7h8rsPsLIHWzgEWNeDXr9YRxRYfDii2MgbtnzWnI63vy9akiSNh
    Ed/hpHAK5TPfinnZlKqQuetOmQ/ey54jPqTo6BLDPubiYk4okKriPs12WoijcbM/
    CzXS0c4CXoLiMfp3ho8w5plwQKqcg5Eda8J7S0vtnRNp8HUkxboJm1L83knENBat
    O3zLZQnpD3r1O4jv1hjkVOJ9tz+ZyuoTnPks6c7lGY6n2VHSN800vCrB/ybb0q7C
    fq4a/87WJ/ChjVv8e2+R8NUbHQIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYD
    VR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUnLsbrlkeRm96d/anNGoOVtR49XAwDQYJ
    KoZIhvcNAQELBQADggEBAHh5AaBV5PXsDCSmATZWeYIwPLKnBWMqOhJ8oT1TQnlv
    1dYzfweFgA8zwMCsWiDgtTss2fxk/MMFOht0Z0KVfQXVSDNZP0m+8jI1i9dE1oRS
    BRV2kWp/1HluMBoTtLrxP27GJY9frGAoXgFuoRzz8qsPw8W1IojxkSYjE9bJumoW
    85LL7+XtgfX7b/7sjadez6dNPOLeYk9qdAhVG+nuMeA1gpUDMEIV0Z9YHLWRBhTs
    NObsX17N5ntr2N0lxRn2XprkI+sq/M703rdgQCgGo6S6rEMQiOPTq96x1RsT2La8
    vDWDXgDqVc/gZ9Jwcv3jD5gtzlmwuZ359ATA+Q02ZVo=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDlzCCAn+gAwIBAgIIYAeHnbflbnIwDQYJKoZIhvcNAQELBQAwWTFXMFUGA1UE
    AwxOb3BlbnNoaWZ0LWt1YmUtYXBpc2VydmVyLW9wZXJhdG9yX2xvY2FsaG9zdC1y
    ZWNvdmVyeS1zZXJ2aW5nLXNpZ25lckAxNzc0ODU5MzIxMB4XDTI2MDMzMDA4Mjg0
    MFoXDTM2MDMyNzA4Mjg0MVowWTFXMFUGA1UEAwxOb3BlbnNoaWZ0LWt1YmUtYXBp
    c2VydmVyLW9wZXJhdG9yX2xvY2FsaG9zdC1yZWNvdmVyeS1zZXJ2aW5nLXNpZ25l
    ckAxNzc0ODU5MzIxMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA33Qb
    6hLRuU99sqKMABvUTnlFfh7xArKQpbYvLkVZfC30Kb8bXmKPQbcP/1fDMLeiFfuH
    Guj69WlqFn2EKCRGAinJ0h5uGZQhmlnAN3q9Zz7xs48wtlySy7jZWTG5eGvX+RQO
    0FoXg+UxxuqQ5aB7B2eXQAq9hLV/2v6UWbriI7Wbj5LwF+U3FSgbbLQUbTTLhcQE
    D+W9JztdN+/lxKu/btc/MhyG5ZDqV4BtycXod9eDtR/j3XXqA7jRGLwLn/IY5JPE
    I64b01fBWVFL43gWmawkDjND/taEXkIJtVLdSHW/T0UxPLfSgeCgJvouz+qCDSQb
    OGgY9tf+XoMe2yBRmQIDAQABo2MwYTAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/
    BAUwAwEB/zAdBgNVHQ4EFgQUoF56LseA5ADWCiITRJHtspVVAC8wHwYDVR0jBBgw
    FoAUoF56LseA5ADWCiITRJHtspVVAC8wDQYJKoZIhvcNAQELBQADggEBANOkXKFx
    lRm4hhJvIDCPiIEbutMwu8HNj28xsDBCQE/L1ULxIhs+5REaJ8ageG2Oqwa8twaY
    4aP514dsggBHW8p7ZgbtjoI05HSFqbTSeqHLM8TeVi8G6k77SSrP+hmDWLuWwNAH
    UI0auADelacCIVLUcg4SE2MetO/7a/dNy+Dk3jRMSz4xKrwZKN/71jeFoG9MmQ70
    f811YVWSP/MsY2tZZ9jB71TIA4XDnV/eQKDQAXh+bBj4T3zyjKW2n55HOYyrDc/+
    uYUfQHQt56ep7yeNWurVJ8Sz/MF2W6iyEuLfZsqvtWJ9dmnDk09zuqiE+iRXJWQq
    GztifW1jXhmxhaE=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDlzCCAn+gAwIBAgIIFqtiQO0Yg/QwDQYJKoZIhvcNAQELBQAwJjEkMCIGA1UE
    AwwbaW5ncmVzcy1vcGVyYXRvckAxNzc0ODU5MzY5MB4XDTI2MDMzMDA4MjkyOVoX
    DTI4MDMyOTA4MjkzMFowOzE5MDcGA1UEAwwwKi5hcHBzLm9hZHAtNTgzMS5xZS5n
    Y3AuZGV2Y2x1c3Rlci5vcGVuc2hpZnQuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEAunoAhPRA35J2CeFDoSG4qEwKrDZN1t+6HDXa9i/DeBsb/hfw
    De9tbPF2bB4CWznNraF9aR3Jr6qH2M7paHJnh/nuvVtgBTfHM4ze8DeCsU9gbEgK
    kxuZSHixZ1vp/vFZMjonWQcx4PzoK1u3ZCXbpXXzhxiOy5w/dDy/cwpGJtn6+3A3
    VRpKYskdqYENZ0YCXaMeCtyqVrniSENeyRNLeQWDRbomVD+ev5lUlAOyDe5q+i9g
    FDBtqlnGMvmRQ0fsuSCLjrWjrqkfI7UhPqtj9zsaqFBiAhMXObl9W77rLXw6P7Pz
    6xDX+Ex2tG09WrL+Rf8QuxZ7ZcwPhMHrMCJEYwIDAQABo4GzMIGwMA4GA1UdDwEB
    /wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB0GA1Ud
    DgQWBBQgHclToWqzoSUklU2IHwMxs2N0NzAfBgNVHSMEGDAWgBQic3swtboCpIVD
    GaiUQP1vPezixzA7BgNVHREENDAygjAqLmFwcHMub2FkcC01ODMxLnFlLmdjcC5k
    ZXZjbHVzdGVyLm9wZW5zaGlmdC5jb20wDQYJKoZIhvcNAQELBQADggEBAEFK71Kg
    lVux1SOAGyCXQMfvHydDFNreinTmHuAzVH2Z1fPW/3cIrcXK8ElYPyNjz1h8y7V8
    BqVF2teMAe5H8Yy2nZPOBYgRtUnaDHT0ifNFkSObFs7B3rJh8yXoRkqF+qAO9HHS
    R4AiG1tyZxSQzSFWABdsbBpIQUjIAC1WDUu+KRQo5Srbv4IMFquZLJWPqiNaFr5F
    +iW/SYy27GEImZmHvzRK7X7sA3QNrr2qGyXbEGmWqzun3wTwDkj0HUAVtSye4zD6
    suBR7f9zBwzfbgCU/mkFjUTdD298hVS+7/J4pe08o33yhrqzNIjoYU7TyGxzziX3
    Qav9D9EatHvnphc=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDDDCCAfSgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtpbmdy
    ZXNzLW9wZXJhdG9yQDE3NzQ4NTkzNjkwHhcNMjYwMzMwMDgyOTI5WhcNMjgwMzI5
    MDgyOTMwWjAmMSQwIgYDVQQDDBtpbmdyZXNzLW9wZXJhdG9yQDE3NzQ4NTkzNjkw
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC4Y4dh7pZlCsLtP3a97OdA
    8NJTOfQdYdi3JuacuW8LXigOgDp/o13qOM+ojSuDVdxx9uc1XjVrWvRjo8hRh6Xy
    AxBR+J/4BQrWflEHd+nBCEf8TV8zzgwM5g1TvPHh09SVupyGSfx1E0K+xuie9Inx
    AMRlWiLVcr9Ncqdbk4ENVRCFLXNfAOFi1MHGs+sdGI+W+6ECdajU/elrcBf/hrwc
    Ox4egZAv7Ty38AKod6vHXAOkpsVILGvPOMIYVTz7Dok3Mf++FDFUdz0c+fJ44/wp
    sV+Dz5J8l6Xh+ewd3IBsyplavWp7mBTz6BX9Br1DvGEDP1+23y7Z3X7K0zkJL0ND
    AgMBAAGjRTBDMA4GA1UdDwEB/wQEAwICpDASBgNVHRMBAf8ECDAGAQH/AgEAMB0G
    A1UdDgQWBBQic3swtboCpIVDGaiUQP1vPezixzANBgkqhkiG9w0BAQsFAAOCAQEA
    DCeZ7wKzjN1UeOsIdBA54yW2lmzuKzjGlwz21YI+/zcs/iCpyXlPdlOjctCIhUqt
    dzYNTNdR72k9sfe7xXgbjRPy9uPfgQgHCTU5xt3hjhRO9Ub620a1bPZGV9T9PxPy
    0qj/4bBLbLMUcMYM5CO+V8gDfvWtJOzxECmUmyrGnLjCZ3RK6wG7wOEtEB/8SSpG
    QmheuqK1yo+2kKnnr2KCHj2mxPFHVpq+F3URw/iOhOAeEdpmZR5Wryb7qSQ7saOC
    79IkxRGE1fMvh0q/+00QMWK2fjXktBaWZlhk0k5dtLojaL5cPKk8cqejueqlwE5M
    9edf3iSgrsx9aKotIdBMLg==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  creationTimestamp: "2026-03-30T15:21:32Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/description: {}
    manager: kube-controller-manager
    operation: Update
    time: "2026-03-30T15:21:32Z"
  name: kube-root-ca.crt
  namespace: crane-complex-demo
  resourceVersion: "157110"
  uid: bcb59de9-0b37-4058-a633-45ecf0334288
