apiVersion: v1
data:
  placeholder: bm90LWEtcmVhbC1jcmVkZW50aWFs
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"demo-dummy-secret","namespace":"crane-complex-demo"},"stringData":{"placeholder":"not-a-real-credential"},"type":"Opaque"}
  creationTimestamp: "2026-03-30T15:21:52Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:placeholder: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2026-03-30T15:21:52Z"
  name: demo-dummy-secret
  namespace: crane-complex-demo
  resourceVersion: "157292"
  uid: 6860321f-3926-45ad-81b8-bbe889b537c3
type: Opaque
