apiVersion: v1
imagePullSecrets:
- name: app-sa-dockercfg-72h8g
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"app-sa","namespace":"crane-complex-demo"}}
    openshift.io/internal-registry-pull-secret-ref: app-sa-dockercfg-72h8g
  creationTimestamp: "2026-03-30T15:21:43Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:imagePullSecrets: {}
      f:metadata:
        f:annotations:
          f:openshift.io/internal-registry-pull-secret-ref: {}
      f:secrets:
        k:{"name":"app-sa-dockercfg-72h8g"}: {}
    manager: openshift.io/image-registry-pull-secrets_service-account-controller
    operation: Apply
    time: "2026-03-30T15:21:43Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2026-03-30T15:21:43Z"
  name: app-sa
  namespace: crane-complex-demo
  resourceVersion: "157224"
  uid: e8564b10-6eb5-4f5e-849f-2e61990b625a
secrets:
- name: app-sa-dockercfg-72h8g
