apiVersion: v1
data:
  data: test data 37
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:06Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:06Z"
  name: test-cm-37
  namespace: default
  resourceVersion: "443"
  uid: 85a5962e-64cf-40eb-b025-128800bbce56
