apiVersion: v1
data:
  data: test data 465
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:20Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:20Z"
  name: test-cm-465
  namespace: default
  resourceVersion: "882"
  uid: 532965a4-7316-489e-96e0-2c459dac14c7
