apiVersion: v1
data:
  data: test data 444
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:20Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:20Z"
  name: test-cm-444
  namespace: default
  resourceVersion: "861"
  uid: cca06a23-abf4-4e2c-b39e-923350c97892
