apiVersion: v1
data:
  data: test data 55
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:07Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:07Z"
  name: test-cm-55
  namespace: default
  resourceVersion: "462"
  uid: afd86e68-d625-4469-8619-86b0a1537e6b
