apiVersion: v1
data:
  data: test data 173
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:11Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:11Z"
  name: test-cm-173
  namespace: default
  resourceVersion: "583"
  uid: 8bf1ec11-c6f9-4bb9-99d6-88455aeefe3c
