apiVersion: v1
data:
  data: test data 309
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:15Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:15Z"
  name: test-cm-309
  namespace: default
  resourceVersion: "721"
  uid: a4c21a51-e2ea-47d7-9183-0a579d8c5558
