apiVersion: v1
data:
  data: test data 16
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:06Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:06Z"
  name: test-cm-16
  namespace: default
  resourceVersion: "420"
  uid: 0cddb4b6-dc4b-495e-9b97-01f29158355b
