apiVersion: v1
data:
  data: test data 500
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:22Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:22Z"
  name: test-cm-500
  namespace: default
  resourceVersion: "918"
  uid: d72a6fe3-a090-4650-a0e9-02e052321601
