apiVersion: v1
data:
  data: test data 407
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:19Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:19Z"
  name: test-cm-407
  namespace: default
  resourceVersion: "823"
  uid: cbb70866-b6f6-475c-9f81-8d8d7fe834b6
