apiVersion: v1
data:
  data: test data 91
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:08Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:08Z"
  name: test-cm-91
  namespace: default
  resourceVersion: "499"
  uid: 9967c3ae-33b9-480e-9e06-2cd3bf7aaefe
