apiVersion: v1
data:
  data: test data 324
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:16Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:16Z"
  name: test-cm-324
  namespace: default
  resourceVersion: "738"
  uid: ab194d61-5464-44e7-b21e-e42d65fe55ff
