apiVersion: v1
data:
  data: test data 442
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:20Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:20Z"
  name: test-cm-442
  namespace: default
  resourceVersion: "859"
  uid: ff447ffb-bbae-48cd-8530-0e53ca461e9f
