apiVersion: v1
data:
  data: test data 454
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:20Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:20Z"
  name: test-cm-454
  namespace: default
  resourceVersion: "871"
  uid: ce003d18-ed62-46b9-9bdf-71655d847923
