apiVersion: v1
data:
  data: test data 437
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:19Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:19Z"
  name: test-cm-437
  namespace: default
  resourceVersion: "854"
  uid: bffc9ebc-f082-4e1f-a059-94cd970bf891
