apiVersion: v1
data:
  data: test data 165
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:11Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:11Z"
  name: test-cm-165
  namespace: default
  resourceVersion: "574"
  uid: 7d2d2a50-82e2-4de8-94dd-ad2616af2b37
