apiVersion: v1
data:
  data: test data 308
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:15Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:15Z"
  name: test-cm-308
  namespace: default
  resourceVersion: "720"
  uid: 919eb88f-2bc4-4961-baa3-382b42253ce6
