apiVersion: v1
data:
  data: test data 369
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:17Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:17Z"
  name: test-cm-369
  namespace: default
  resourceVersion: "785"
  uid: 1c35c9c3-888d-4238-9a0e-048f3607ad4f
