apiVersion: v1
data:
  data: test data 54
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:07Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:07Z"
  name: test-cm-54
  namespace: default
  resourceVersion: "461"
  uid: 9985acea-2403-47ba-9b09-47497dccacff
