apiVersion: v1
data:
  data: test data 288
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:15Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:15Z"
  name: test-cm-288
  namespace: default
  resourceVersion: "700"
  uid: cdcf7782-dada-4fe2-bed2-aa2f9672431e
