apiVersion: v1
data:
  data: test data 154
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:10Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:10Z"
  name: test-cm-154
  namespace: default
  resourceVersion: "563"
  uid: 82926cd9-57d7-4500-a8e6-71fec01bbd84
