apiVersion: v1
data:
  data: test data 372
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:17Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:17Z"
  name: test-cm-372
  namespace: default
  resourceVersion: "788"
  uid: 6b325e68-d801-4ae8-8fbe-a5a0dd988fb6
