apiVersion: v1
data:
  data: test data 58
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:07Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:07Z"
  name: test-cm-58
  namespace: default
  resourceVersion: "466"
  uid: 52f320f2-7f5f-4c05-95de-a99ab70c7c53
