apiVersion: v1
data:
  data: test data 227
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:13Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:13Z"
  name: test-cm-227
  namespace: default
  resourceVersion: "638"
  uid: 9b1fa2fb-6591-42c9-93ba-df79a9615209
