apiVersion: v1
data:
  data: test data 395
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:18Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:18Z"
  name: test-cm-395
  namespace: default
  resourceVersion: "811"
  uid: 934c5e46-bb1f-4abb-b973-94949822f2ca
