apiVersion: v1
data:
  data: test data 441
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:20Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:20Z"
  name: test-cm-441
  namespace: default
  resourceVersion: "858"
  uid: c46f97a4-3789-4b32-9203-80c19d60db9b
