apiVersion: v1
data:
  data: test data 238
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:13Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:13Z"
  name: test-cm-238
  namespace: default
  resourceVersion: "649"
  uid: 1b7504fb-5349-4741-9927-6e52a28fae93
