apiVersion: v1
data:
  data: test data 59
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:07Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:07Z"
  name: test-cm-59
  namespace: default
  resourceVersion: "467"
  uid: 1f1560d4-93e4-4e91-a5fc-7a50393bdd34
