apiVersion: v1
data:
  data: test data 215
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:12Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:12Z"
  name: test-cm-215
  namespace: default
  resourceVersion: "625"
  uid: 11a58da7-b96b-486d-81da-d8e3048afba2
