apiVersion: v1
data:
  data: test data 96
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:08Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:08Z"
  name: test-cm-96
  namespace: default
  resourceVersion: "504"
  uid: 15f0fc98-3b86-476c-b9f0-a67257070622
