apiVersion: v1
data:
  data: test data 293
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:15Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:15Z"
  name: test-cm-293
  namespace: default
  resourceVersion: "705"
  uid: e52aa8d6-1117-4a23-87ca-5126da7a7c52
