apiVersion: v1
data:
  data: test data 410
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:19Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:19Z"
  name: test-cm-410
  namespace: default
  resourceVersion: "827"
  uid: bf6cc8c5-a86b-4771-ab9f-b4571df03e51
