apiVersion: v1
data:
  data: test data 384
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:18Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:18Z"
  name: test-cm-384
  namespace: default
  resourceVersion: "800"
  uid: 5250310c-55d2-491d-aa66-ae6ee7fcbe89
