apiVersion: v1
data:
  data: test data 332
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:16Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:16Z"
  name: test-cm-332
  namespace: default
  resourceVersion: "746"
  uid: e3f1cff5-543e-476c-81bd-343ffdde22e6
