apiVersion: v1
data:
  data: test data 325
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:16Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:16Z"
  name: test-cm-325
  namespace: default
  resourceVersion: "739"
  uid: 24b52291-ce06-43b0-aa12-5359e0faa091
