apiVersion: v1
data:
  data: test data 201
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:12Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:12Z"
  name: test-cm-201
  namespace: default
  resourceVersion: "611"
  uid: 5d345f90-73d1-41ac-b445-12570b93f32c
