apiVersion: v1
data:
  data: test data 318
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:16Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:16Z"
  name: test-cm-318
  namespace: default
  resourceVersion: "731"
  uid: 04961009-1b70-4366-99c8-2a18e1370f98
