apiVersion: v1
data:
  data: test data 467
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:20Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:20Z"
  name: test-cm-467
  namespace: default
  resourceVersion: "884"
  uid: e840c836-14d0-415d-a660-cf4b46fb685c
