apiVersion: v1
data:
  data: test data 459
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:20Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:20Z"
  name: test-cm-459
  namespace: default
  resourceVersion: "876"
  uid: 26e2913d-84cc-4f0b-856d-527a6ca2c771
