apiVersion: v1
data:
  data: test data 277
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:14Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:14Z"
  name: test-cm-277
  namespace: default
  resourceVersion: "688"
  uid: 0570a76c-1e38-4993-bf14-5755be73012f
