apiVersion: v1
data:
  data: test data 267
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:14Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:14Z"
  name: test-cm-267
  namespace: default
  resourceVersion: "678"
  uid: e21a3caf-98b5-4043-9335-c68f42f83f24
