apiVersion: v1
data:
  data: test data 281
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:14Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:14Z"
  name: test-cm-281
  namespace: default
  resourceVersion: "692"
  uid: 001e02eb-5b36-476e-9ffe-1fcdfa75e599
