apiVersion: v1
data:
  data: test data 152
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:10Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:10Z"
  name: test-cm-152
  namespace: default
  resourceVersion: "561"
  uid: 402ed4a1-4dd1-44c0-bd96-8e249e141c54
