apiVersion: v1
data:
  data: test data 432
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:19Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:19Z"
  name: test-cm-432
  namespace: default
  resourceVersion: "849"
  uid: d0baa975-ac71-471a-bde6-06076fc3b07a
