apiVersion: v1
data:
  data: test data 283
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:14Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:14Z"
  name: test-cm-283
  namespace: default
  resourceVersion: "694"
  uid: f354de93-7f76-41c7-87fc-ec221edaa817
