apiVersion: v1
data:
  data: test data 105
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:09Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:09Z"
  name: test-cm-105
  namespace: default
  resourceVersion: "513"
  uid: cea88e52-8754-48eb-afb5-c4d10f6e3f3a
