apiVersion: v1
data:
  data: test data 181
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:11Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:11Z"
  name: test-cm-181
  namespace: default
  resourceVersion: "591"
  uid: 1b60f617-663a-4b57-a252-0324dd9da8ff
