apiVersion: v1
data:
  data: test data 402
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:18Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:18Z"
  name: test-cm-402
  namespace: default
  resourceVersion: "818"
  uid: f66a8a47-f443-40c4-88e9-9531e75c8f54
