apiVersion: v1
data:
  data: test data 253
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:13Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:13Z"
  name: test-cm-253
  namespace: default
  resourceVersion: "664"
  uid: c7aba614-ba89-46d1-a19b-fde397d56ac8
