apiVersion: v1
data:
  data: test data 452
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:20Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:20Z"
  name: test-cm-452
  namespace: default
  resourceVersion: "869"
  uid: efa327ce-c6d5-4a83-958e-135f0a92ec60
