apiVersion: v1
data:
  data: test data 176
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:11Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:11Z"
  name: test-cm-176
  namespace: default
  resourceVersion: "586"
  uid: c4e1993b-289d-4b5b-b58a-2f3502826cbe
