apiVersion: v1
data:
  data: test data 476
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:21Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:21Z"
  name: test-cm-476
  namespace: default
  resourceVersion: "894"
  uid: 400510d7-78c3-4ea2-8168-78c54804849a
