apiVersion: v1
data:
  data: test data 264
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:14Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:14Z"
  name: test-cm-264
  namespace: default
  resourceVersion: "675"
  uid: 510f9af6-1c55-4f71-b70d-af2901943589
