apiVersion: v1
data:
  data: test data 211
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:12Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:12Z"
  name: test-cm-211
  namespace: default
  resourceVersion: "621"
  uid: 1c0f4876-7d51-4dd2-b78c-b888e825643c
