apiVersion: v1
data:
  data: test data 35
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:06Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:06Z"
  name: test-cm-35
  namespace: default
  resourceVersion: "441"
  uid: bfd4895a-18f8-4805-a705-38fc6df5d55e
