apiVersion: v1
data:
  data: test data 25
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:06Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:06Z"
  name: test-cm-25
  namespace: default
  resourceVersion: "430"
  uid: faaf10cb-c9c2-4014-9efc-4e04f69fab01
