apiVersion: v1
data:
  data: test data 27
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:06Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:06Z"
  name: test-cm-27
  namespace: default
  resourceVersion: "432"
  uid: 78ed2a60-3fac-403c-9e2d-5cd936af81e8
