apiVersion: v1
data:
  data: test data 411
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:19Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:19Z"
  name: test-cm-411
  namespace: default
  resourceVersion: "828"
  uid: 51e086d9-4d32-4a7f-926b-242f7909121c
