apiVersion: v1
data:
  data: test data 41
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:06Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:06Z"
  name: test-cm-41
  namespace: default
  resourceVersion: "447"
  uid: a6684ec6-beb7-4c9c-b98a-f9fa98265e89
