apiVersion: v1
data:
  data: test data 466
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:20Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:20Z"
  name: test-cm-466
  namespace: default
  resourceVersion: "883"
  uid: f56a57c3-1ec7-46e4-8d71-5a60ad686ec8
