apiVersion: v1
data:
  data: test data 489
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:21Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:21Z"
  name: test-cm-489
  namespace: default
  resourceVersion: "907"
  uid: 55e7af27-e296-4c6e-9f55-63705c4ebcf6
