apiVersion: v1
data:
  data: test data 127
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:09Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:09Z"
  name: test-cm-127
  namespace: default
  resourceVersion: "536"
  uid: c577618a-0de1-409c-a1de-dcf7d8ed86fe
