apiVersion: v1
data:
  data: test data 474
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:21Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:21Z"
  name: test-cm-474
  namespace: default
  resourceVersion: "892"
  uid: d728b124-545d-4569-8372-ab356e95dd67
