apiVersion: v1
data:
  data: test data 112
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:09Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:09Z"
  name: test-cm-112
  namespace: default
  resourceVersion: "521"
  uid: 0ae71eb2-e87d-4b74-b21c-995ae21ea3d0
