apiVersion: v1
data:
  data: test data 230
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:13Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:13Z"
  name: test-cm-230
  namespace: default
  resourceVersion: "641"
  uid: bec67453-f088-4e38-8f4e-28527d8088e2
