apiVersion: v1
data:
  data: test data 355
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:17Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:17Z"
  name: test-cm-355
  namespace: default
  resourceVersion: "770"
  uid: fe89a4be-b65b-4313-be2f-3ca997572c99
