apiVersion: v1
data:
  data: test data 262
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:14Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:14Z"
  name: test-cm-262
  namespace: default
  resourceVersion: "673"
  uid: 408d1d90-aa77-4a8e-8150-330e12656ef3
