apiVersion: v1
data:
  data: test data 70
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:07Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:07Z"
  name: test-cm-70
  namespace: default
  resourceVersion: "478"
  uid: f381acc1-1d68-49df-bfba-1248d0401073
