apiVersion: v1
data:
  data: test data 278
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:14Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:14Z"
  name: test-cm-278
  namespace: default
  resourceVersion: "689"
  uid: 5f36286e-04a8-4b5d-91f4-8f313b1a8365
