apiVersion: v1
data:
  data: test data 184
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:11Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:11Z"
  name: test-cm-184
  namespace: default
  resourceVersion: "594"
  uid: ab6c59b1-b58b-43e0-9fb9-0a09c123f5c5
