apiVersion: v1
data:
  data: test data 435
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:19Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:19Z"
  name: test-cm-435
  namespace: default
  resourceVersion: "852"
  uid: 41d195e7-321e-4f2a-a7a0-c42e3701e119
