apiVersion: v1
data:
  data: test data 62
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:07Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:07Z"
  name: test-cm-62
  namespace: default
  resourceVersion: "470"
  uid: 2964857b-b6f2-4dee-9faa-6fc8293421d6
