apiVersion: v1
data:
  data: test data 370
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:17Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:17Z"
  name: test-cm-370
  namespace: default
  resourceVersion: "786"
  uid: 680f2418-289b-4cb4-ad77-c68f6dd2c154
