apiVersion: v1
data:
  data: test data 208
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:12Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:12Z"
  name: test-cm-208
  namespace: default
  resourceVersion: "618"
  uid: 975a70bd-02a2-417a-97cc-a57799d1b2ca
