apiVersion: v1
data:
  data: test data 95
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:08Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:08Z"
  name: test-cm-95
  namespace: default
  resourceVersion: "503"
  uid: c65a1c74-a7c1-4705-8b8e-75797e37deaa
