apiVersion: v1
data:
  data: test data 157
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:10Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:10Z"
  name: test-cm-157
  namespace: default
  resourceVersion: "566"
  uid: 2a55dc48-3afa-47de-aaea-fb8ef2b827fd
