apiVersion: v1
data:
  data: test data 224
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:13Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:13Z"
  name: test-cm-224
  namespace: default
  resourceVersion: "634"
  uid: e0ec6690-bf8e-4992-b1d8-f4575f2da128
