apiVersion: v1
data:
  data: test data 69
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:07Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:07Z"
  name: test-cm-69
  namespace: default
  resourceVersion: "477"
  uid: eeaf9e0d-0547-44fb-a89f-d82a70ab982d
