apiVersion: v1
data:
  data: test data 272
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:14Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:14Z"
  name: test-cm-272
  namespace: default
  resourceVersion: "683"
  uid: f86a316a-7cb7-46e1-a33c-9b261229dd8a
