apiVersion: v1
data:
  data: test data 415
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:19Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:19Z"
  name: test-cm-415
  namespace: default
  resourceVersion: "832"
  uid: 04429d0a-d9d1-47d4-9047-0f91d00747c1
