apiVersion: v1
data:
  data: test data 364
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:17Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:17Z"
  name: test-cm-364
  namespace: default
  resourceVersion: "780"
  uid: c90dd8e1-99e4-4fc6-9c6a-0f5cb8c3fc77
