apiVersion: v1
data:
  data: test data 295
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:15Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:15Z"
  name: test-cm-295
  namespace: default
  resourceVersion: "707"
  uid: 8f651f4a-bb5a-40fc-829f-9e01d616e314
