apiVersion: v1
data:
  data: test data 72
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:07Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:07Z"
  name: test-cm-72
  namespace: default
  resourceVersion: "480"
  uid: eddf6bc5-cfb9-4940-9276-63a755d1c501
