apiVersion: v1
data:
  data: test data 386
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:18Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:18Z"
  name: test-cm-386
  namespace: default
  resourceVersion: "802"
  uid: bc7efa98-7224-46a6-98c7-46a89ac64052
