apiVersion: v1
data:
  data: test data 285
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:15Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:15Z"
  name: test-cm-285
  namespace: default
  resourceVersion: "696"
  uid: 23ab1d65-aee4-4108-ad06-6548b1a94fbb
