apiVersion: v1
data:
  data: test data 362
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:17Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:17Z"
  name: test-cm-362
  namespace: default
  resourceVersion: "778"
  uid: 21058b5a-c5b7-4561-88ef-1766c77b10f4
