apiVersion: v1
data:
  data: test data 223
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:13Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:13Z"
  name: test-cm-223
  namespace: default
  resourceVersion: "633"
  uid: ae21667c-2794-48a2-99bf-34ee081536b3
