apiVersion: v1
data:
  data: test data 18
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:06Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:06Z"
  name: test-cm-18
  namespace: default
  resourceVersion: "422"
  uid: 868fafdd-0648-4fb5-bc0a-93f5dd0e437b
