apiVersion: v1
data:
  data: test data 222
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:12Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:12Z"
  name: test-cm-222
  namespace: default
  resourceVersion: "632"
  uid: d1cc8e7b-8b5d-426a-b744-838ebb6ba4a1
