apiVersion: v1
data:
  data: test data 76
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:08Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:08Z"
  name: test-cm-76
  namespace: default
  resourceVersion: "484"
  uid: 4e662ffe-d473-4190-890c-b6908b2de943
