apiVersion: v1
data:
  data: test data 56
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:07Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:07Z"
  name: test-cm-56
  namespace: default
  resourceVersion: "463"
  uid: 9876d216-d287-4895-a6ce-d1cd1fe7654a
