apiVersion: v1
data:
  data: test data 320
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:16Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:16Z"
  name: test-cm-320
  namespace: default
  resourceVersion: "733"
  uid: e8b6b977-add7-4993-8e1f-16731ef15f91
