apiVersion: v1
data:
  data: test data 57
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:07Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:07Z"
  name: test-cm-57
  namespace: default
  resourceVersion: "464"
  uid: 57cf88f6-3ae8-4197-85e0-1257e89a5b64
