apiVersion: v1
data:
  data: test data 141
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:10Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:10Z"
  name: test-cm-141
  namespace: default
  resourceVersion: "550"
  uid: cd2966aa-569e-44db-a08c-6342a38ced35
