apiVersion: v1
data:
  data: test data 276
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:14Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:14Z"
  name: test-cm-276
  namespace: default
  resourceVersion: "687"
  uid: 4b197e85-b16b-404a-b2da-9751804cb7b4
