apiVersion: v1
data:
  data: test data 413
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:19Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:19Z"
  name: test-cm-413
  namespace: default
  resourceVersion: "830"
  uid: 46ea9c61-30e7-4697-b61a-d6a59954b372
