apiVersion: v1
data:
  data: test data 179
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:11Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:11Z"
  name: test-cm-179
  namespace: default
  resourceVersion: "589"
  uid: 6af327be-f581-40b7-89a4-7942a03ae8f9
