apiVersion: v1
data:
  data: test data 169
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:11Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:11Z"
  name: test-cm-169
  namespace: default
  resourceVersion: "579"
  uid: dae30d62-6fbb-497b-8c38-8bf75d65bfe7
