apiVersion: v1
data:
  data: test data 1
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:05Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:05Z"
  name: test-cm-1
  namespace: default
  resourceVersion: "404"
  uid: 63203645-76f6-45c8-a8d0-252997a1e7f6
