apiVersion: v1
data:
  data: test data 338
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:16Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:16Z"
  name: test-cm-338
  namespace: default
  resourceVersion: "752"
  uid: 285647de-7f10-4042-b067-64357842a6fa
