apiVersion: v1
data:
  data: test data 14
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:06Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:06Z"
  name: test-cm-14
  namespace: default
  resourceVersion: "418"
  uid: ba3de9b7-3bc3-46a8-9f81-376e2010819a
