apiVersion: v1
data:
  data: test data 322
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:16Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:16Z"
  name: test-cm-322
  namespace: default
  resourceVersion: "735"
  uid: 4dbffc5c-2a32-4342-93e5-9787915c7b3c
