apiVersion: v1
data:
  data: test data 456
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:20Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:20Z"
  name: test-cm-456
  namespace: default
  resourceVersion: "873"
  uid: 1f146112-2d6d-4e36-ad19-035b1d50cb76
