apiVersion: v1
data:
  data: test data 111
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:09Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:09Z"
  name: test-cm-111
  namespace: default
  resourceVersion: "520"
  uid: 82883f05-3bbb-4c36-afca-943ba679b30d
