apiVersion: v1
data:
  data: test data 83
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:08Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:08Z"
  name: test-cm-83
  namespace: default
  resourceVersion: "491"
  uid: 77457bdd-8f34-4445-9f5a-5f5a18ff9714
