apiVersion: v1
data:
  data: test data 317
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:16Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:16Z"
  name: test-cm-317
  namespace: default
  resourceVersion: "730"
  uid: cbca4683-50b7-43d5-9d6f-a09d3d81011b
