apiVersion: v1
data:
  data: test data 190
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:11Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:11Z"
  name: test-cm-190
  namespace: default
  resourceVersion: "600"
  uid: 39db3115-9a97-487b-ab1e-920ddf4b078e
