apiVersion: v1
data:
  data: test data 343
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:16Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:16Z"
  name: test-cm-343
  namespace: default
  resourceVersion: "757"
  uid: 2e959c85-9e4f-4eaa-a372-bc19242b94e2
