apiVersion: v1
data:
  data: test data 53
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:07Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:07Z"
  name: test-cm-53
  namespace: default
  resourceVersion: "460"
  uid: 7f48b80e-157b-441d-8cb0-b9847e1bc8a5
