apiVersion: v1
data:
  data: test data 307
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:15Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:15Z"
  name: test-cm-307
  namespace: default
  resourceVersion: "719"
  uid: a91595ea-3d23-4507-830e-f9214bc2990c
