apiVersion: v1
data:
  data: test data 298
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:15Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:15Z"
  name: test-cm-298
  namespace: default
  resourceVersion: "710"
  uid: 4d885b4e-0b10-4ffd-933a-685688ed5a9f
