apiVersion: v1
data:
  data: test data 145
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:10Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:10Z"
  name: test-cm-145
  namespace: default
  resourceVersion: "554"
  uid: c2b028c8-c415-4374-8ce9-ecfb22fa01e5
