apiVersion: v1
data:
  data: test data 296
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:15Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:15Z"
  name: test-cm-296
  namespace: default
  resourceVersion: "708"
  uid: d0217fbb-702c-468a-8e01-76405ae5cb89
