apiVersion: v1
data:
  data: test data 445
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:20Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:20Z"
  name: test-cm-445
  namespace: default
  resourceVersion: "862"
  uid: 83fb1a5b-8bf0-46c5-8a5c-de9349b7851b
