apiVersion: v1
data:
  data: test data 337
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:16Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:16Z"
  name: test-cm-337
  namespace: default
  resourceVersion: "751"
  uid: 1d1e981d-117c-4544-9d7d-6ec65c68afba
