apiVersion: v1
data:
  data: test data 310
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-28T08:35:15Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2026-05-28T08:35:15Z"
  name: test-cm-310
  namespace: default
  resourceVersion: "722"
  uid: 1b66d671-627b-4c3a-bad4-ca6c6a0681eb
