apiVersion: v1
data:
  service-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDUTCCAjmgAwIBAgIIZqyIdI72MQIwDQYJKoZIhvcNAQELBQAwNjE0MDIGA1UE
    Awwrb3BlbnNoaWZ0LXNlcnZpY2Utc2VydmluZy1zaWduZXJAMTc4NTI5OTI3OTAe
    Fw0yNjA3MjkwNDI3NTlaFw0yODA5MjYwNDI4MDBaMDYxNDAyBgNVBAMMK29wZW5z
    aGlmdC1zZXJ2aWNlLXNlcnZpbmctc2lnbmVyQDE3ODUyOTkyNzkwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDLMGWscRza/5CDJXibKR0gBXDyZHkDBFyG
    UZHHPMD+kBEY0Dd4GyXr6qRLsZVGb98UKOVM2zxu6HBzSvyaFex/AyeU8Gv1gXHt
    WslQjbk3hG2t8k8jGNTBn3pz6gOXOAdvdhjfTjinAEnkiajoQdq2fq9m2+QgowY2
    G5smFmC2d6OpfeKxDQ9VL0N/KHfMRqnlV16ktsQn/YewwevwISJJrDQ3xvET38JY
    Kxj4Fsr+xcND+nKq/3pjFqY1F/mQQi3CeLMulTlvDafGbOFDduPqoL7k6LhW5+7l
    yhwFXfn1RoJqtujOTqhWZoq+1cFRph7SfcLvvL70N/jQzW3vC+wTAgMBAAGjYzBh
    MA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQe0G5N
    3AAHoT0aUl4JzVp17uA41TAfBgNVHSMEGDAWgBQe0G5N3AAHoT0aUl4JzVp17uA4
    1TANBgkqhkiG9w0BAQsFAAOCAQEAhq7iu31m5Jx9QRcoLuYDYGpEDlXBkpdL7UEF
    w1Q7w081J8f48xr2+R/kzRKHDKGpDtUENj2VR9rSJIjnlsm6/1lqtG6KaZR4Fi6y
    GprYP6K2tLcIF3Y41YQ4Gv2gMnRf0ZoNYAI3OZSLooM4vhRyMFCZlfnrke5TABLI
    hpf7YzoxleFPHFKjPGjgk9UpphVFpchri1Gv9n3n0MJP8vAv9I5T4wzQgbVZaml9
    WdXff34r78u/g7g9u1n9wX8ngSoGByy7Vyrdk2Ff8SZ2WJsGtGqQ05cgamyiCCHb
    jji3oOFOWxLDxpDX/CE8PG+/IXIoE7DwWLNoFntfOjyCgFWqAg==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  creationTimestamp: "2026-07-29T11:56:52Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data: {}
      f:metadata:
        f:annotations:
          .: {}
          f:service.beta.openshift.io/inject-cabundle: {}
    manager: kube-controller-manager
    operation: Update
    time: "2026-07-29T11:56:52Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:service-ca.crt: {}
    manager: service-ca-operator
    operation: Update
    time: "2026-07-29T11:56:52Z"
  name: openshift-service-ca.crt
  namespace: redis
  resourceVersion: "133781"
  uid: d7c48f25-8f13-442e-9c7a-075236e4a781
