apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDMjCCAhqgAwIBAgIIWhqGRrDrzlAwDQYJKoZIhvcNAQELBQAwNzESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSEwHwYDVQQDExhrdWJlLWFwaXNlcnZlci1sYi1zaWduZXIw
    HhcNMjYwNzI5MDQxMjIzWhcNMzYwNzI2MDQxMjIzWjA3MRIwEAYDVQQLEwlvcGVu
    c2hpZnQxITAfBgNVBAMTGGt1YmUtYXBpc2VydmVyLWxiLXNpZ25lcjCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBALmDDTGr+bpb+16L+umYHZkQz9NH3gyw
    sY9gWan2t8GIfH2vS7CbbRNeLiHs/kIojBKfvl55nqZJjcdiovMptDJhye0PzzDj
    A1k75YcBZxJIvTbYqrw8g41CgVoq6ie91rW1MCDxoNUExeL0l2lMotXMPihfljxg
    dxM6k9p3dCavPhxc2djptdM4216lPqcvDONMQKu9u6taU8eIP58+8VRYHaPmZ+tu
    18+9vvvK0vVy7RzIyu58m5SEoo7g7rLcKDS01fEpd3SwcnLGJAu3nH1zrJy52R1S
    V+OP1/RFnLGepDgilgQdzS5bcUJh6bS2YHmxFMuSe6Y9bMVrgUdyW28CAwEAAaNC
    MEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFCRJ
    UhLpTsSSGNt4oWam39bSH0NXMA0GCSqGSIb3DQEBCwUAA4IBAQAoI/0xhP37aUvP
    GT1ejrSDHZHKL2kIpoLSJ4XskF0pu7wJpDOJ/ZZd9PraPHbDmhaL+Sj5i1dHcuog
    AsPljiOBM2XszTf1/jVoNbVtqeZHNA2yAS9S3FK2NgiSe3qZdt4tBanCAz8Vmdo8
    NopLBLkPCLyAhq95UhLWfB9I9tFU/Fj24uGji2zIPG29H28QNdzopjTYZIWGsgr1
    RmrGphHAKu7X2ObXaBKNgrtNvenYdi9nJKEmLpuEAO/0JUG0UkNBJvSUddNTmFxZ
    kNZaOpAJ2OxU7mS+z7BscV40lWAmBNTSzfiVCumCN7H+goyZmjtxYeM2N/LAkP1z
    mm5LNysB
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDQDCCAiigAwIBAgIIKFrxFadTVs4wDQYJKoZIhvcNAQELBQAwPjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSgwJgYDVQQDEx9rdWJlLWFwaXNlcnZlci1sb2NhbGhvc3Qt
    c2lnbmVyMB4XDTI2MDcyOTA0MTIyM1oXDTM2MDcyNjA0MTIyM1owPjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSgwJgYDVQQDEx9rdWJlLWFwaXNlcnZlci1sb2NhbGhvc3Qt
    c2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtTSIp3C+bjBv
    n9jyY3DmqjYiVHUMrGEVUjDATeHbNreo0oC9B6EnTTspTFvOHs0r80i1kry2XEyw
    OKFdJaloa8H3gSXAp11Da45xJM5SzVeIln6RySLtiOjeG4O6dXxgakVUXSg3KnBG
    Elrc8H/6A2K7AVWEEonvQ37S8wtuNNgKrET1pjLuJCWFoEASxHklyUYC9MT3jGbC
    hlr/N3772rRhzbEp+jLMMImiItQW+Eg7wak4t9UbohaNNo1Q+alWrz29enlZRpCC
    nYWnStxsPheduR+xIchkux7gSqC+VzwGHgLcxjpSIBpO+Dsi9ZqFefAx+zvGfIxE
    DOFu2OdGrwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB
    /zAdBgNVHQ4EFgQUE65reJigFKAk+rkmYa4+EHnOc7QwDQYJKoZIhvcNAQELBQAD
    ggEBAII0qokTJtFx9vZW7eUVwGGGkb8vEt31nlvfI2+WKkRWMqLsLVdrIrvDFv4o
    oTxBWCLaQ79Vft4E7cjgh8f08h5bBv6iCLJp8UMBb4g6bOtGWFTntIb08CwZh/vV
    ICNRBeH6pnAU0lGK7koAAi1CRWD+u5j0bWFaDlGhIU6nwhKyLJAjnmCvK/4hbPNG
    3nmdtJEp1kxcqiUq7iA5fWL7GtjvZL9Ivl0fqOn1sCDvMHBU26vXnGNWnDwWubM4
    HGyt/7g3dWCORQY/ddknnXMlAQoD16q2/DHLvLCRN+L3h4ZXGzpdUL8K93wNIQx2
    QQjcVAg3Yl0AFC+DGHgp1Dnlwho=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIIRi/MIHnkUxkwDQYJKoZIhvcNAQELBQAwRDESMBAGA1UE
    CxMJb3BlbnNoaWZ0MS4wLAYDVQQDEyVrdWJlLWFwaXNlcnZlci1zZXJ2aWNlLW5l
    dHdvcmstc2lnbmVyMB4XDTI2MDcyOTA0MTIyM1oXDTM2MDcyNjA0MTIyM1owRDES
    MBAGA1UECxMJb3BlbnNoaWZ0MS4wLAYDVQQDEyVrdWJlLWFwaXNlcnZlci1zZXJ2
    aWNlLW5ldHdvcmstc2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
    AQEA5LWJcfavzKMdtTHCpQ6w874nhDBzkHUdE+QFdeosWtzmBXD9I3N3Hp7GsiWF
    twKIsXCngCtMgZeuYku2zT0JMNz4m1RdZU4HjVqIYX4B8vCSh2K4P7QfXB85zDZZ
    YV//exF3NJgSaVgZIJPZWYjHBQe2DtVOY7J2mupzx5wpBKKcd4AFU1AqZMETevbV
    2GXek6bE7C2j+qW2dmpGRXk8hWM8cm9We6uCycWtNQjhRoMHaMk2FO4RFVAtIYcz
    tLLr2NMXHBGJwJynC00b0AP71cnD6NnfJTg3TJh5pJj2XTOvPbMIX5sIhuU5iAUa
    7bJwiAOZZ+G6GTKWsk4DFdzcSwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYD
    VR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUPi64sFd/DiqTkwoqR1xJnSWTWaowDQYJ
    KoZIhvcNAQELBQADggEBAGHc0Bi9+tpo9LgDCLPv+g5HaFO3ATsu7w48yuDtlI9f
    BBvxLzny97nAh6/mPlMbZfjadrXb6GxDz7//JIr5L49CxIDwsNWlZ7PO+SkHC9TQ
    MoGoZAqRY5xu9y30l/QSsYyz45VpF+l3mFQjYgV8ao0r43Jik/fIwZtlzO3/0JMO
    yBjHYP0BELnVCpKsStStoLs75yhb//XYA7C9xFtRSnKAdbWFMr1TP00pwe6xUcPB
    lqwshe0DvX4d3q4MFWJ0vGn044ZGT0Q9TLg3mxkskBsSkMwJB3x6OHaPofMRMXll
    VvW+CE3Gm2lkpHTD/YW+4c5NvinuQv5/FPM9mMjxFuM=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDlzCCAn+gAwIBAgIIYrUApGEIppMwDQYJKoZIhvcNAQELBQAwWTFXMFUGA1UE
    AwxOb3BlbnNoaWZ0LWt1YmUtYXBpc2VydmVyLW9wZXJhdG9yX2xvY2FsaG9zdC1y
    ZWNvdmVyeS1zZXJ2aW5nLXNpZ25lckAxNzg1Mjk5MjgwMB4XDTI2MDcyOTA0Mjc1
    OVoXDTM2MDcyNjA0MjgwMFowWTFXMFUGA1UEAwxOb3BlbnNoaWZ0LWt1YmUtYXBp
    c2VydmVyLW9wZXJhdG9yX2xvY2FsaG9zdC1yZWNvdmVyeS1zZXJ2aW5nLXNpZ25l
    ckAxNzg1Mjk5MjgwMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuOnr
    QwrC3IARjfHaxR3Esn1emFDSnEHQWojiXxNo4xuMph0W1IKelETXDb3b+rJV4DtJ
    kCT2Tob2lDPYLDCaAkIZV1x9H2jBNuIU150xhuPy+Ob8zRiOZRTQmxbW7Utkr+zO
    nbZZ3Wo2rVI07TSsTtE3OZQIj7Jy8rlUuxiuzgXoXkicXZnKZ0tRO4es69t0UxQ5
    ST6IV/rBmwzXoDpSFx+iflax4KYn967FAYOQ5t7iAOXC7+7CHyWsPtkjoxl69h7I
    3yT8vimJPc3KRxsN9WxTvM927FVtzxnJBFuFwwYKJzsm+KqqV1U3Znvk1UBPyxld
    64uc/2CYtRg8kgHjjwIDAQABo2MwYTAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/
    BAUwAwEB/zAdBgNVHQ4EFgQURpigJaoVjceFbUKbRebjblCPccQwHwYDVR0jBBgw
    FoAURpigJaoVjceFbUKbRebjblCPccQwDQYJKoZIhvcNAQELBQADggEBAICkMv5C
    hBQk+Y3tFjW53NazcYjyZ/1XzHu4mYacM1vxsHZLF+pNbEkR8WkRmiFJkIV4n8SZ
    nyKoTIFbx+ajJlEN9oR/iX+dEsi6DOfkmC7izYFmE+0E/BHpPEJHIWLvAhcQD7EF
    z1wtK1JfZilRM/PxMRKqTS2KY1Mj87hWKyvdpNyNVnJsNn0rxsfkdhSxlisnhUQU
    qHmSDUqoBP2KAoUvAHGFP7F0ccOoNEqNjbwmB6QdgjfcxCAKLrG3qxRlaOtsQLjQ
    H6qUYlFxJb+VndcI/JRgOsrnLo7jaUOqsvW3y0gaM3GMzyG35pf9lAi6pDfWXx+F
    +QIShitXZ4w7ChI=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDkzCCAnugAwIBAgIId3wv8mIhakIwDQYJKoZIhvcNAQELBQAwJjEkMCIGA1UE
    AwwbaW5ncmVzcy1vcGVyYXRvckAxNzg1Mjk5MzU1MB4XDTI2MDcyOTA0MjkxNloX
    DTI4MDcyODA0MjkxN1owOTE3MDUGA1UEAwwuKi5hcHBzLm1pZ3FlLTY2NDMxLnFl
    LmRldmNsdXN0ZXIub3BlbnNoaWZ0LmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEP
    ADCCAQoCggEBAOuzc2uY0NavHYaNr3wFmmhv7PYQEADqksl5Z5UgxFjqIYWXZBI7
    QTh76h1/lDJjIvywp2f6KwqNtxqGqBMAlMcEyXhfnv0AlVeL/ZPTyH9wrmipk4XB
    +oMAncK2T5CJZ9sMe2hzmZlJn5eKmHKjUWsZoMaLNu79HMJFWRr/xbl2XuEQWFDh
    r6/tYebFVmiWaCqB3Un+qpnjpwTlOQqRoUpn/euWs85vMr0nOwJthBigeRsQpMtw
    puqKus5cEAYvGlQzZG+h/nFhC+g4IreRIUiEeu/jM3J61UvsVq6LOeLnI6owu8n6
    9rtQy2xyE7T4erxXXV52OD3SheNh7K6P9jsCAwEAAaOBsTCBrjAOBgNVHQ8BAf8E
    BAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAdBgNVHQ4E
    FgQURdJY3LJFTJZcpTcCNXTTaVKsqpswHwYDVR0jBBgwFoAUu5aXDvkJk1mSW8YU
    ucWE2fSeoyIwOQYDVR0RBDIwMIIuKi5hcHBzLm1pZ3FlLTY2NDMxLnFlLmRldmNs
    dXN0ZXIub3BlbnNoaWZ0LmNvbTANBgkqhkiG9w0BAQsFAAOCAQEABsmKPz0ngh7o
    w8eEvywQuIWAalK68sA7ZPXGBhZMk+wtvblcL8FUJncbvyo+FdzgJL6Esb0LVWwS
    U3QtVELfyn/VtJfH0pNQcrBtoxMGQ+wLUaCYOxriUs7S850LmyWUk6Go2RCKg24f
    l168AB2M/Qa//OPcDwd2ob/B9TydqfIRSPlZvaoQPB4lzQKeJUiO9GX1WKgQhGER
    IBzJDXb5dPgaNm4Ri71lEExtqPEYU3ruWQ8EZ6bqX22rJ6xLofg0X+avINZvFERh
    XAPDlsfszZqX8pYxy5g93zEE0YrKiAraydZasq2eVk6XImPb02yoNV2d8xD24blF
    1yuqKvAn1g==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDDDCCAfSgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtpbmdy
    ZXNzLW9wZXJhdG9yQDE3ODUyOTkzNTUwHhcNMjYwNzI5MDQyOTE2WhcNMjgwNzI4
    MDQyOTE3WjAmMSQwIgYDVQQDDBtpbmdyZXNzLW9wZXJhdG9yQDE3ODUyOTkzNTUw
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDEbyzl8Q3ZLMdw2xaTqSKX
    viFab3Fi/FUreWyiH35S9nghk4K8m5y4YlpRR48o9/wsxpOpzU4k3pt5dqw/x4gm
    1aDuCbD+L/JRnUWjLQV3EAEZHXO6Fgat3PA/Sw2ZKEsHo4o3+zhYBFVAZbhHJP3c
    1/AT/sTM8pM/X82/U+LPp6mH4zZ/yiJvNUq65M0ougaxr1XK67jhd58+5/jWWdzH
    5pFW9Cxy69w1H0tpamad8cQ9bbzfBoKMB04dsb7zprufkB2r3WDGGmAnGS8mNd6a
    7ndOaU89MtnO1YUwlYfR3DauE/kK/Ib6Md2KXgUp/KNf8PqeKLeJyDDg1P2n6d7/
    AgMBAAGjRTBDMA4GA1UdDwEB/wQEAwICpDASBgNVHRMBAf8ECDAGAQH/AgEAMB0G
    A1UdDgQWBBS7lpcO+QmTWZJbxhS5xYTZ9J6jIjANBgkqhkiG9w0BAQsFAAOCAQEA
    orqXfEOXP0mN3zgrYP+XAdZq7W5NCurPXK7CTwegEUuJjcLc7ubFKlY26gshU+kx
    truAZ9WVcvQaIisubEAohTxLtEQ60C9euakmICAhJXVZKxXFrcv4xkufhz8o2fWz
    QQiPcv99Pi5NSPuIEzndkmf5EinpPsPY4hB3OvBWQ9aoISZEFr7ro1dnOLNeiUzp
    3q13kIdnThcmCBknnHefpAFzbflN+KdOxZW6Ol9HWkwmSQYUngPVPTENteLZ0tHW
    q5hTGBX5TIRsrcUKb/U6NYb6f5JDX4mAOnWkB4xf4aN7K69d21Fh71CM4c7Ts1SO
    9a1Po3eD1lXH7N/4H8OdKA==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  creationTimestamp: "2026-07-29T11:56:52Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/description: {}
    manager: kube-controller-manager
    operation: Update
    time: "2026-07-29T11:56:52Z"
  name: kube-root-ca.crt
  namespace: redis
  resourceVersion: "133775"
  uid: 13eaf43a-55b7-47f6-ab4a-5475e526137f
