apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2026-07-29T11:56:57Z"
  labels:
    endpoints.kubernetes.io/managed-by: endpoint-controller
    name: redis
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:endpoints.kubernetes.io/managed-by: {}
          f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2026-07-29T11:57:08Z"
  name: redis
  namespace: redis
  resourceVersion: "134036"
  uid: 16d11b11-a4f1-4395-8a59-d2aa5d52f2ee
