apiVersion: v1
data:
  redis-password: UEFTU1dPUkQ=
kind: Secret
metadata:
  creationTimestamp: "2026-07-29T11:56:55Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:redis-password: {}
      f:type: {}
    manager: OpenAPI-Generator
    operation: Update
    time: "2026-07-29T11:56:55Z"
  name: redis
  namespace: redis
  resourceVersion: "133801"
  uid: 2534e8f3-8e56-4067-89af-d02c846ef69f
type: Opaque
