apiVersion: v1
imagePullSecrets:
- name: default-dockercfg-jpgs2
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: default-dockercfg-jpgs2
  creationTimestamp: "2026-07-29T11:56:52Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:imagePullSecrets: {}
      f:metadata:
        f:annotations:
          f:openshift.io/internal-registry-pull-secret-ref: {}
      f:secrets:
        k:{"name":"default-dockercfg-jpgs2"}: {}
    manager: openshift.io/image-registry-pull-secrets_service-account-controller
    operation: Apply
    time: "2026-07-29T11:56:52Z"
  name: default
  namespace: redis
  resourceVersion: "133777"
  uid: 8c9992b4-af7a-466d-87b4-7b47cc7c2bb3
secrets:
- name: default-dockercfg-jpgs2
