apiVersion: v1
imagePullSecrets:
- name: builder-dockercfg-lgfpb
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: builder-dockercfg-lgfpb
  creationTimestamp: "2026-07-29T11:56:52Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:imagePullSecrets: {}
      f:metadata:
        f:annotations:
          f:openshift.io/internal-registry-pull-secret-ref: {}
      f:secrets:
        k:{"name":"builder-dockercfg-lgfpb"}: {}
    manager: openshift.io/image-registry-pull-secrets_service-account-controller
    operation: Apply
    time: "2026-07-29T11:56:52Z"
  name: builder
  namespace: redis
  resourceVersion: "133780"
  uid: 65e40fd1-e248-4de3-be35-80849ead02b0
secrets:
- name: builder-dockercfg-lgfpb
