apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: eGFJMmdpdWhxc2V0TC82VDRaOVViUT09
  MYSQL_WORDPRESS_PASSWORD: QzZUa25lcFo3Vm5idTdGZVdBSUFidz09
  WORDPRESS_ADMIN_PASSWORD: d0ZoSytaZDhlU2RhVmx1Ug==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"MYSQL_ROOT_PASSWORD":"eGFJMmdpdWhxc2V0TC82VDRaOVViUT09","MYSQL_WORDPRESS_PASSWORD":"QzZUa25lcFo3Vm5idTdGZVdBSUFidz09","WORDPRESS_ADMIN_PASSWORD":"d0ZoSytaZDhlU2RhVmx1Ug=="},"kind":"Secret","metadata":{"annotations":{},"name":"wordpress-secrets-hg692g82th","namespace":"default"},"type":"Opaque"}
  creationTimestamp: "2026-04-10T12:15:07Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:MYSQL_ROOT_PASSWORD: {}
        f:MYSQL_WORDPRESS_PASSWORD: {}
        f:WORDPRESS_ADMIN_PASSWORD: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2026-04-10T12:15:07Z"
  name: wordpress-secrets-hg692g82th
  namespace: default
  resourceVersion: "676"
  uid: 0bb63c2c-fa4a-4c86-ad5d-141dccbd25ad
type: Opaque
