apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2026-04-10T05:05:02Z"
  creationTimestamp: "2026-04-10T05:05:01Z"
  labels:
    app: simple-nginx-nopv
    endpoints.kubernetes.io/managed-by: endpoint-controller
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:endpoints.kubernetes.io/last-change-trigger-time: {}
        f:labels:
          .: {}
          f:app: {}
          f:endpoints.kubernetes.io/managed-by: {}
      f:subsets: {}
    manager: kube-controller-manager
    operation: Update
    time: "2026-04-10T05:05:02Z"
  name: my-simple-nginx-nopv
  namespace: simple-nginx-nopv
  resourceVersion: "1083690"
  uid: 50068ac5-9627-48a7-9177-9c4017c40e89
subsets:
- addresses:
  - ip: 10.244.3.191
    nodeName: src
    targetRef:
      kind: Pod
      name: simple-nginx-nopv-deployment-764987f958-6m454
      namespace: simple-nginx-nopv
      uid: 1deb4311-5096-40e7-89a7-42463d889c3c
  ports:
  - port: 8080
    protocol: TCP
