apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2026-04-10T05:05:01Z"
  name: default
  namespace: simple-nginx-nopv
  resourceVersion: "1083666"
  uid: 1fd89539-ada1-4eea-bba1-3f3d66f640b2
