addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.244.0.5
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: minikube
  targetRef:
    kind: Pod
    name: wordpress-74b89cc84c-nm9f8
    namespace: default
    uid: 608501ac-fd76-48a1-b9ef-058b7a6ade67
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2026-04-10T12:16:04Z"
  creationTimestamp: "2026-04-10T12:15:07Z"
  generateName: wordpress-
  generation: 2
  labels:
    app: wordpress
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: wordpress
  managedFields:
  - apiVersion: discovery.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:addressType: {}
      f:endpoints: {}
      f:metadata:
        f:annotations:
          .: {}
          f:endpoints.kubernetes.io/last-change-trigger-time: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:endpointslice.kubernetes.io/managed-by: {}
          f:kubernetes.io/service-name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"9bd59883-6312-4534-a2c1-b71911612715"}: {}
      f:ports: {}
    manager: kube-controller-manager
    operation: Update
    time: "2026-04-10T12:16:04Z"
  name: wordpress-wpfqk
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: wordpress
    uid: 9bd59883-6312-4534-a2c1-b71911612715
  resourceVersion: "810"
  uid: 1a4fffdb-dbcd-4729-905b-11be74b19710
ports:
- name: ""
  port: 80
  protocol: TCP
