apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2026-04-10T12:15:58Z"
  creationTimestamp: "2026-04-10T12:15:07Z"
  labels:
    app: wordpress
    endpoints.kubernetes.io/managed-by: endpoint-controller
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:endpoints.kubernetes.io/last-change-trigger-time: {}
        f:labels:
          .: {}
          f:app: {}
          f:endpoints.kubernetes.io/managed-by: {}
      f:subsets: {}
    manager: kube-controller-manager
    operation: Update
    time: "2026-04-10T12:15:58Z"
  name: wordpress-mysql
  namespace: default
  resourceVersion: "797"
  uid: c2cf2659-9d5c-4f2e-9e3f-6da1b9c6f2c0
subsets:
- addresses:
  - ip: 10.244.0.6
    nodeName: minikube
    targetRef:
      kind: Pod
      name: wordpress-mysql-9474c86b-fr65w
      namespace: default
      uid: f81b40e3-ff85-46ca-8b0a-5c826b78f0c8
  ports:
  - port: 3306
    protocol: TCP
