apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-04-10T12:15:08Z"
  generateName: wordpress-74b89cc84c-
  generation: 1
  labels:
    app: wordpress
    pod-template-hash: 74b89cc84c
    tier: frontend
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:pod-template-hash: {}
          f:tier: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"7ed37255-e5ff-4e33-837d-f584a536d2b8"}: {}
      f:spec:
        f:containers:
          k:{"name":"nginx"}:
            .: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":80,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
            f:resources: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/etc/nginx/nginx.conf"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:subPath: {}
              k:{"mountPath":"/var/www/html"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:readOnly: {}
          k:{"name":"wordpress"}:
            .: {}
            f:env:
              .: {}
              k:{"name":"WORDPRESS_CONFIG_EXTRA"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"WORDPRESS_DB_HOST"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"WORDPRESS_DB_PASSWORD"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:secretKeyRef: {}
              k:{"name":"WORDPRESS_DB_USER"}:
                .: {}
                f:name: {}
                f:value: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":9000,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
            f:resources: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/var/www/html"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
        f:volumes:
          .: {}
          k:{"name":"nginx-config"}:
            .: {}
            f:configMap:
              .: {}
              f:defaultMode: {}
              f:name: {}
            f:name: {}
          k:{"name":"wordpress-persistent-storage"}:
            .: {}
            f:name: {}
            f:persistentVolumeClaim:
              .: {}
              f:claimName: {}
    manager: kube-controller-manager
    operation: Update
    time: "2026-04-10T12:15:08Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          .: {}
          k:{"type":"PodScheduled"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: kube-scheduler
    operation: Update
    subresource: status
    time: "2026-04-10T12:15:08Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:observedGeneration: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:observedGeneration: {}
            f:status: {}
            f:type: {}
          k:{"type":"PodReadyToStartContainers"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:observedGeneration: {}
            f:status: {}
            f:type: {}
          k:{"type":"PodScheduled"}:
            f:observedGeneration: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:observedGeneration: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:hostIPs: {}
        f:observedGeneration: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.244.0.5"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    subresource: status
    time: "2026-04-10T12:16:04Z"
  name: wordpress-74b89cc84c-nm9f8
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: wordpress-74b89cc84c
    uid: 7ed37255-e5ff-4e33-837d-f584a536d2b8
  resourceVersion: "808"
  uid: 608501ac-fd76-48a1-b9ef-058b7a6ade67
spec:
  containers:
  - env:
    - name: WORDPRESS_DB_HOST
      value: wordpress-mysql
    - name: WORDPRESS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: MYSQL_WORDPRESS_PASSWORD
          name: wordpress-secrets-hg692g82th
    - name: WORDPRESS_DB_USER
      value: wordpress
    - name: WORDPRESS_CONFIG_EXTRA
      value: |
        // Set SITE URL dynamically from requests to allow reach it on different endpoints
        if (isset($_SERVER['HTTP_HOST'])) {
            $protocol = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on') ? 'https' : 'http';
            if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
                $protocol = 'https';
            }
            define('WP_HOME', $protocol . '://' . $_SERVER['HTTP_HOST']);
            define('WP_SITEURL', $protocol . '://' . $_SERVER['HTTP_HOST']);
        }
    image: wordpress:6-fpm-alpine
    imagePullPolicy: IfNotPresent
    name: wordpress
    ports:
    - containerPort: 9000
      name: fastcgi
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/www/html
      name: wordpress-persistent-storage
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-gksj7
      readOnly: true
  - image: nginx:alpine
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/www/html
      name: wordpress-persistent-storage
      readOnly: true
    - mountPath: /etc/nginx/nginx.conf
      name: nginx-config
      subPath: nginx.conf
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-gksj7
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: wordpress-persistent-storage
    persistentVolumeClaim:
      claimName: wordpress-pv-claim
  - configMap:
      defaultMode: 420
      name: nginx-config
    name: nginx-config
  - name: kube-api-access-gksj7
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-04-10T12:16:04Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-04-10T12:15:08Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-04-10T12:16:04Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-04-10T12:16:04Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-04-10T12:15:08Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://9deeeda1697dc879391836b269f936362a2e1a77d5beb289889639e352d9ee13
    image: nginx:alpine
    imageID: docker-pullable://nginx@sha256:582c496ccf79d8aa6f8203a79d32aaf7ffd8b13362c60a701a2f9ac64886c93d
    lastState: {}
    name: nginx
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-04-10T12:16:04Z"
    volumeMounts:
    - mountPath: /var/www/html
      name: wordpress-persistent-storage
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /etc/nginx/nginx.conf
      name: nginx-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-gksj7
      readOnly: true
      recursiveReadOnly: Disabled
  - containerID: docker://dd83b5ffcde3a21dcfc1f3fedfeefcc0a7e8e7f63b31817029d370b0ddde48f4
    image: wordpress:6-fpm-alpine
    imageID: docker-pullable://wordpress@sha256:658bc068c60dcd43f2e2deee4b8495ca5e37ef09481d790ad05f99e6a15f61aa
    lastState: {}
    name: wordpress
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-04-10T12:15:33Z"
    volumeMounts:
    - mountPath: /var/www/html
      name: wordpress-persistent-storage
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-gksj7
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.61.192
  hostIPs:
  - ip: 192.168.61.192
  observedGeneration: 1
  phase: Running
  podIP: 10.244.0.5
  podIPs:
  - ip: 10.244.0.5
  qosClass: BestEffort
  startTime: "2026-04-10T12:15:08Z"
