name: Minikube Same Network Smoke

on:
  push:

jobs:
  deploy-app:
    runs-on: ubuntu-22.04
    timeout-minutes: 35
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup minikube clusters
        uses: ./.github/actions/setup-minikube-clusters
        with:
          cpus: max
          memory: "8192"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Clone k8s-apps-deployer
        run: git clone https://github.com/stillalearner/k8s-apps-deployer.git

      - name: Create venv and install package
        run: |
          cd k8s-apps-deployer
          python3 -m venv venv
          echo "$PWD/venv/bin" >> $GITHUB_PATH
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install -e .

      - name: Deploy app on src cluster
        working-directory: k8s-apps-deployer
        run: |
          echo "Deploy app on src cluster"
          k8sdeploy --context src deploy simple-nginx-nopv -n nginx
          echo "Validating the app"
          k8sdeploy --context src validate simple-nginx-nopv -n nginx
          echo "See the pods"
          kubectl get pods -n nginx --context src
