name: Nightly Build Crane Binaries (release-0.10)

on:
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-release-0-10:
    uses: ./.github/workflows/reusable-build-release-binaries.yml
    with:
      checkout_ref: release-0.10
