name: PR Convetions Checks

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify PR contents
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check Title
      id: verifier
      uses: konveyor/release-tools/cmd/verify-pr@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
