name: Run Crane E2E Tests

on:
  pull_request:
  workflow_dispatch:
jobs:
  run-e2e:
    runs-on: ubuntu-22.04
    timeout-minutes: 35
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup minikube clusters
        uses: ./.github/actions/setup-minikube-clusters
        with:
          cpus: max
          memory: "8192"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Clone k8s-apps-deployer
        run: git clone https://github.com/stillalearner/k8s-apps-deployer.git -b fix-context-big

      - name: Create venv and install package
        run: |
          cd k8s-apps-deployer
          python3 -m venv venv
          echo "$PWD/venv/bin" >> $GITHUB_PATH
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install -e .

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install Ginkgo CLI
        run: |
          GINKGO_VERSION="$(go list -m -f '{{.Version}}' github.com/onsi/ginkgo/v2)"
          go install github.com/onsi/ginkgo/v2/ginkgo@"$GINKGO_VERSION"
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          ginkgo version

      - name: Build crane CLI
        run: go build -o crane .

      - name: Run crane e2e tests
        run: |
          ginkgo run -v e2e/tests -- \
            --k8sdeploy-bin="k8sdeploy" \
            --crane-bin="${{ github.workspace }}/crane" \
            --source-context=src \
            --target-context=tgt
