apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2026-03-24T09:41:14Z"
  labels:
    endpoints.kubernetes.io/managed-by: endpoint-controller
    name: redis
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:endpoints.kubernetes.io/last-change-trigger-time: {}
        f:labels:
          .: {}
          f:endpoints.kubernetes.io/managed-by: {}
          f:name: {}
      f:subsets: {}
    manager: kube-controller-manager
    operation: Update
    time: "2026-04-10T05:03:35Z"
  name: redis
  namespace: redis
  resourceVersion: "1083295"
  uid: 8a63539c-6d98-4cbc-a089-e33582a58544
