apiVersion: v1
data:
  redis-password: UEFTU1dPUkQ=
kind: Secret
metadata:
  creationTimestamp: "2026-03-24T09:41:14Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:redis-password: {}
      f:type: {}
    manager: OpenAPI-Generator
    operation: Update
    time: "2026-03-24T09:41:14Z"
  name: redis
  namespace: redis
  resourceVersion: "466863"
  uid: 8819c384-29f4-4b61-9f80-972a4a61452f
type: Opaque
