apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-03-24T09:41:14Z"
  labels:
    name: redis
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:name: {}
      f:spec:
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":6379,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: OpenAPI-Generator
    operation: Update
    time: "2026-03-24T09:41:14Z"
  name: redis
  namespace: redis
  resourceVersion: "466865"
  uid: 8721ae4e-0585-404d-8966-3ba0aee75ed8
spec:
  clusterIP: 10.104.141.22
  clusterIPs:
  - 10.104.141.22
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
